'use client';
import {useState,useMemo,useEffect,useRef} from 'react';
import {createBrowserClient} from '@supabase/ssr';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export default function SignIn({url,publishableKey}:{url:string;publishableKey:string}){
 const db=useMemo(()=>url&&publishableKey?createBrowserClient(url,publishableKey):null,[url,publishableKey]);
 const locked=useRef(false);const [cooldown,setCooldown]=useState(0);
 useEffect(()=>{const messages:Record<string,string>={expired:'That sign-in link has expired or has already been used. Request one new link, then open only the newest email.',browser:'The link could not be matched to this browser. Request one new link here and open it in this same Chrome profile.',connection:'The sign-in connection failed. Please try again.',configuration:'The newsroom connection needs attention. Please contact the owner.'};const error=new URLSearchParams(window.location.search).get('error');if(error)setMessage(messages[error]||messages.expired);const timer=setInterval(()=>setCooldown(Math.max(0,Math.ceil((Number(sessionStorage.getItem('newsroom-resend-after'))-Date.now())/1000))),1000);return()=>clearInterval(timer);},[]);
 const [email,setEmail]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function submit(event:React.FormEvent){event.preventDefault();if(!db||locked.current||Date.now()<Number(sessionStorage.getItem('newsroom-resend-after')))return;locked.current=true;setBusy(true);sessionStorage.setItem('newsroom-resend-after',String(Date.now()+60000));setCooldown(60);setMessage('');
 try{const {error}=await db.auth.signInWithOtp({email:email.trim(),options:{shouldCreateUser:true,emailRedirectTo:'https://todayuk-newsroom.digitalunicorn.chatgpt.site/auth/callback'}});setMessage(error?(error.status===429?'Please wait before requesting another email. If a link already arrived, use the newest one.':'The sign-in email could not be sent. Please try again after the countdown.'):'Check your email for a secure sign-in link. Open it in this browser.');}catch{setMessage('The connection failed. Please retry.')}finally{locked.current=false;setBusy(false)}}
 return <main className="desk" style={{maxWidth:620,paddingTop:80}}><a href="/" className="brand">TODAY<span style={{color:'#b52639'}}>UK</span></a><section className="panel mt-8"><p className="eyebrow">CR News</p><h1>Newsroom sign-in</h1><p className="muted mb-6">Use the email address assigned to your newsroom membership. Signing in does not grant editorial access by itself.</p><form onSubmit={submit}><label htmlFor="email">Email address</label><Input id="email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} className="my-3"/><Button disabled={!db||busy||cooldown>0} type="submit">{busy?'Sending…':cooldown>0?`Request another link in ${cooldown}s`:'Email me a sign-in link'}</Button></form>{!db&&<p className="note">The newsroom connection is being configured.</p>}<p role="status" className="mt-5">{message}</p><a className="inline-block mt-6" href="/live">Already signed in? Open the newsroom →</a></section></main>
}
