'use client';
import {useEffect,useState} from 'react';
import NewsroomNavigation from '@/components/newsroom/navigation';
import {articleWordCount} from '@/lib/editorial/article';
import {suggestedEditorialRisk} from '@/lib/editorial/risk';
type Followup={id:string;task:string;due_at:string;completed:boolean};
type Management={version:number;headline:string;body:string;remote_fingerprint:string|null;remote_modified:string;remote_status:string;checked_at:string;check_message:string;update_state:string;risk_notes:string};
type Article={id:string;draft_id:string;group_id:string;headline:string;body:string;wordpress_url:string;updated_at:string;management:Management|null;followups:Followup[]};
export default function Published(){const [articles,setArticles]=useState<Article[]>([]),[loaded,setLoaded]=useState(false),[message,setMessage]=useState(''),[role,setRole]=useState(''),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[body,setBody]=useState(''),[headline,setHeadline]=useState('');
 async function load(){const r=await fetch('/api/content',{cache:'no-store'}),data=await r.json() as {error?:string;articles:Article[];role:string};if(!r.ok)throw Error(data.error);setArticles(data.articles);setRole(data.role);setLoaded(true);}
 useEffect(()=>{void load().catch(e=>setMessage(e.message));},[]);
 async function act(payload:Record<string,unknown>){setBusy(true);setMessage('Working…');try{const r=await fetch('/api/content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await r.json() as {error?:string;message:string};if(!r.ok)throw Error(data.error);setMessage(data.message);await load();if(payload.action==='update')setEditing(false);return true;}catch(e){setMessage(e instanceof Error?e.message:'Please retry.');return false;}finally{setBusy(false);}}
 useEffect(()=>{if(!selected||role!=='owner'||editing||busy)return;const timer=setInterval(()=>{if(document.visibilityState==='visible')void act({action:'check',id:selected});},300000);return()=>clearInterval(timer);},[selected,role,editing,busy]);
 const a=articles.find(x=>x.id===selected),m=a?.management;
 const overdue=articles.reduce((n,a)=>n+a.followups.filter(f=>!f.completed&&new Date(f.due_at)<new Date()).length,0);
 return <><NewsroomNavigation active="published"/><main className="desk editorial-page"><div className="intro"><div><h1>Published</h1><p>Manage live articles, updates and follow-ups.</p></div><button disabled={busy||editing} onClick={()=>void load().catch(e=>setMessage(e.message))}>Refresh</button></div>{message&&<div role="status" className="note" style={{position:'sticky',top:0,zIndex:10}}>{message}</div>}{!loaded&&!message&&<p>Loading published articles…</p>}{overdue>0&&<p className="note">{overdue} overdue follow-up{overdue===1?'':'s'}.</p>}
 {!a?<><div className="story-grid">{articles.map(s=><article className="panel" key={s.id}><span className="pill">{s.management?.remote_status&&s.management.remote_status!=='publish'?'Needs attention':'Published'}</span><h2 className="my-4">{s.management?.headline??s.headline}</h2><p>{s.followups.filter(f=>!f.completed).length} open follow-ups</p>{s.management?.check_message&&<p className="muted">{s.management.check_message}</p>}<div className="flex gap-3 my-4"><button onClick={()=>{setSelected(s.id);setMessage('');if(role==='owner')void act({action:'check',id:s.id});}}>Manage article →</button><a href={s.wordpress_url} target="_blank" rel="noreferrer">View live ↗</a></div></article>)}</div>{loaded&&!articles.length&&<p>No published articles yet. <a href="/editorial">Open drafts →</a></p>}</>:<><button disabled={editing||busy} onClick={()=>setSelected('')}>← All published articles</button><h2 className="my-4">{m?.headline??a.headline}</h2><p><a href={a.wordpress_url} target="_blank" rel="noreferrer">View live article ↗</a> · <a href={'/research?group='+encodeURIComponent(a.group_id)}>Sources & evidence →</a></p>
 <section className="panel my-6"><h3>Live status</h3><p>{m?.checked_at?'Last checked '+new Date(m.checked_at).toLocaleString('en-GB'):'Not checked yet'}</p><p>{m?.check_message||'Check WordPress for changes before editing.'}</p>{role==='owner'&&<div className="flex flex-wrap gap-3 my-3"><button disabled={busy||editing} onClick={()=>act({action:'check',id:a.id})}>Check live article</button>{m?.update_state&&m.update_state!=='idle'&&<button disabled={busy} onClick={()=>act({action:'reconcile',id:a.id})}>Resolve interrupted update</button>}{m?.check_message.startsWith('Changed in WordPress')&&<button disabled={busy} onClick={()=>{if(window.confirm('Have you reviewed the live changes? This keeps your saved text; a later update replaces the WordPress text.'))void act({action:'accept',id:a.id,confirmed:true});}}>I reviewed the live changes</button>}</div>}<p className="muted text-sm">Checks repeat every five minutes while this article is open and you are not editing. AI development alerts remain paused.</p></section>
 {role==='owner'&&!editing&&<button disabled={busy||!m?.remote_fingerprint||m.update_state!=='idle'||m.check_message.startsWith('Changed in WordPress')} onClick={()=>{setHeadline(m?.headline??a.headline);setBody(m?.body??a.body);setEditing(true);setMessage('');}}>Edit this article</button>}
 {editing&&<form className="panel my-6" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act({action:'update',id:a.id,version:m?.version,headline,body,risk:f.get('risk'),notes:f.get('notes'),checks:f.has('checks')});}}><h3>Update the existing article</h3><label>Headline<input value={headline} onChange={e=>setHeadline(e.target.value)} required maxLength={500}/></label><label>Article<textarea value={body} onChange={e=>setBody(e.target.value)} required rows={18}/></label><p>{articleWordCount(body)} words · minimum 400</p><label>Editorial risk<select name="risk" defaultValue={suggestedEditorialRisk(headline+' '+body)}><option value="standard">Standard</option><option value="sensitive">Sensitive</option></select></label><label>What changed and what did you check?<textarea name="notes" required maxLength={4000} rows={3}/></label><label className="my-4"><input type="checkbox" name="checks" required/> I checked the facts, potential harm and privacy, attribution and rights.</label><div className="flex gap-3"><button disabled={busy||articleWordCount(body)<400}>Save update to WordPress</button><button type="button" disabled={busy} onClick={()=>setEditing(false)}>Cancel edit</button></div></form>}
 <section className="panel my-6"><h3>Follow-ups</h3>{a.followups.map(f=><div key={f.id} className="my-4"><label><input type="checkbox" checked={f.completed} disabled={busy||!['owner','editor'].includes(role)} onChange={e=>act({action:'complete',id:a.id,followup_id:f.id,completed:e.target.checked})}/> {f.task}</label><small>{new Date(f.due_at).toLocaleDateString('en-GB')}{!f.completed&&new Date(f.due_at)<new Date()?' · Overdue':''}</small></div>)}{!a.followups.length&&<p>No follow-ups set.</p>}{['owner','editor'].includes(role)&&<form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);if(await act({action:'followup',id:a.id,task:f.get('task'),due_at:f.get('due_at')}))form.reset();}}><label>Next action<input name="task" placeholder="For example: check whether residents have returned home" required maxLength={2000}/></label><label>Due date<input name="due_at" type="date" required/></label><button disabled={busy}>Add follow-up</button></form>}</section></>}
 </main></>;
}
