import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);
for(const f of (await readdir('supabase/migrations')).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile('supabase/migrations/'+f,'utf8'));
await db.exec(await readFile('supabase/seed.sql','utf8'));
const w='10000000-0000-4000-8000-000000000001',u='30000000-0000-4000-8000-000000000001',v='30000000-0000-4000-8000-000000000002';
await db.exec(`insert into auth.users values('${u}'),('${v}');insert into workspace_members values('${w}','${u}','owner',now()),('${w}','${v}','viewer',now());`);
await db.exec(`select set_config('request.jwt.claim.sub','${u}',false)`);
const g=(await db.query(`insert into story_groups(workspace_id,title) values('${w}','Test') returning id`)).rows[0].id;
const d=(await db.query(`insert into editorial_drafts(workspace_id,group_id,headline,body) values('${w}','${g}','Test','body') returning id`)).rows[0].id;
const id=(await db.query(`insert into wordpress_deliveries(workspace_id,draft_id,draft_revision,headline,body,state,actor_id,wordpress_id) values('${w}','${d}',1,'Test','body','publish','${u}',42) returning id`)).rows[0].id;
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${v}',false);`);
const rpc=(action,values={})=>db.query('select * from public.content_manage($1,$2,$3::jsonb)',[id,action,JSON.stringify(values)]);
await assert.rejects(rpc('check',{fingerprint:'base'}));
await assert.rejects(db.query('insert into content_followups(workspace_id,delivery_id,task,due_at) values($1,$2,$3,now())',[w,id,'task']));
await db.exec(`select set_config('request.jwt.claim.sub','${u}',false)`);
await rpc('check',{fingerprint:'base',status:'publish',message:'Live'});
await assert.rejects(rpc('reserve',{version:1,fingerprint:'different',headline:'Title',body:'Body',checks:true}));
await assert.rejects(rpc('reserve',{fingerprint:'base',headline:'Title',body:'Body',checks:true}));
const reserved=(await rpc('reserve',{version:1,fingerprint:'base',headline:'Updated',body:'New body',checks:true})).rows[0];
assert.equal(reserved.update_state,'updating');
await assert.rejects(rpc('reserve',{version:1,fingerprint:'base',headline:'Other',body:'Other',checks:true}));
await assert.rejects(rpc('finish',{operation:'00000000-0000-0000-0000-000000000000'}));
await rpc('uncertain',{operation:reserved.operation});
await assert.rejects(rpc('reserve',{version:1,fingerprint:'base',headline:'Other',body:'Other',checks:true}));
const reconciled=(await rpc('reconcile',{applied:true,fingerprint:'new',status:'publish',message:'Confirmed'})).rows[0];assert.equal(reconciled.headline,'Updated');assert.equal(reconciled.version,2);assert.equal(reconciled.update_state,'idle');
const f=(await db.query('insert into content_followups(workspace_id,delivery_id,task,due_at) values($1,$2,$3,now()) returning id',[w,id,'Check update'])).rows[0];
await db.query('update content_followups set completed=true where id=$1',[f.id]);
assert.equal((await db.query('select completed from content_followups where id=$1',[f.id])).rows[0].completed,true);
assert.ok((await db.query("select * from audit_events where entity_table='content_management'")).rows.length>=4);
console.log('Content CRM: permissions, stale versions, update locks, uncertain recovery, follow-ups and audits passed.');await db.close();
