import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
let passed=0;
const W='10000000-0000-4000-8000-000000000001', W2='20000000-0000-4000-8000-000000000001';
const owner='30000000-0000-4000-8000-000000000001', outsider='30000000-0000-4000-8000-000000000002', viewer='30000000-0000-4000-8000-000000000003';
const check=(value,message)=>{assert.ok(value,message);passed++;console.log('PASS',message)};
async function denied(sql,code){try{await db.exec(sql);assert.fail('Expected denial: '+sql)}catch(e){assert.equal(e.code,code,sql+' '+e.message);passed++;console.log('PASS rejected',code)}}
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);
await db.exec(await readFile('supabase/migrations/20260910130000_platform_core.sql','utf8'));
await db.exec(await readFile('supabase/seed.sql','utf8'));
await db.exec(await readFile('supabase/seed.sql','utf8'));
check((await db.query('select count(*)::int n from public.hierarchy_nodes')).rows[0].n===9,'idempotent CR seed: one publication, eight districts');
await db.exec(`insert into auth.users values('${owner}'),('${outsider}'),('${viewer}');insert into workspaces(id,slug,name) values('${W2}','other','Other workspace');insert into workspace_members values('${W}','${owner}','owner',now()),('${W2}','${owner}','editor',now()),('${W}','${viewer}','viewer',now());insert into hierarchy_nodes(workspace_id,kind,code,name) values('${W2}','publication','OTHER','Other');`);
const cr=(await db.query("select id from hierarchy_nodes where code='CR'")).rows[0].id;
const cr0=(await db.query("select id from hierarchy_nodes where code='CR0'")).rows[0].id;
const other=(await db.query("select id from hierarchy_nodes where code='OTHER'")).rows[0].id;
await denied(`update hierarchy_nodes set parent_id='${cr0}' where id='${cr}'`,'23514');
await db.exec('set role anon');
for(const t of ['workspaces','workspace_members','hierarchy_nodes','tags','node_tags','module_config','audit_events']) await denied(`select * from ${t}`,'42501');
await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${outsider}',false)`);
check((await db.query('select * from workspaces')).rows.length===0,'non-member sees no workspaces');
await denied(`insert into tags(workspace_id,category,label) values('${W}','topic','Intrusion')`,'42501');
await denied(`insert into workspace_members(workspace_id,user_id,role) values('${W}','${outsider}','owner')`,'42501');
await db.exec(`select set_config('request.jwt.claim.sub','${viewer}',false)`);
check((await db.query('select * from hierarchy_nodes')).rows.length===9,'viewer sees only own workspace nodes');
await denied(`insert into tags(workspace_id,category,label) values('${W}','topic','Viewer edit')`,'42501');
check((await db.query(`update tags set label='changed' returning *`)).rows.length===0,'viewer updates no tags');
await db.exec(`select set_config('request.jwt.claim.sub','${owner}',false)`);
await db.exec(`insert into tags(workspace_id,category,label) values('${W}','topic','Transport')`);
const tag=(await db.query("select id from tags where label='Transport'")).rows[0].id;
check(!!tag,'owner can create tag');
await db.exec(`update tags set label='Local transport' where id='${tag}'`);
check((await db.query(`select * from audit_events where actor_id='${owner}' and entity_table='tags'`)).rows.length===2,'tag insert and update produce attributed audits');
await denied(`update tags set workspace_id='${W2}' where id='${tag}'`,'23514');
await denied(`insert into node_tags(workspace_id,node_id,tag_id,signal) values('${W}','${other}','${tag}','factual')`,'23503');
await denied(`update hierarchy_nodes set parent_id='${cr0}' where id='${cr}'`,'42501');
await db.exec(`update hierarchy_nodes set name='Croydon district' where id='${cr0}'`);
check((await db.query(`select name from hierarchy_nodes where id='${cr0}'`)).rows[0].name==='Croydon district','owner may edit node display name');
await denied('delete from audit_events','42501');
await denied("update audit_events set action='fabricated'",'42501');
await denied("update workspace_members set role='owner'",'42501');
await denied('update module_config set enabled=true','42501');
check((await db.query('select * from module_config where enabled')).rows.length===0,'all workflows start disabled');
console.log(`${passed} checks passed. Embedded PostgreSQL; Supabase integration remains a separate check.`);
await db.close();
