import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();const W='10000000-0000-4000-8000-000000000001',U='30000000-0000-4000-8000-000000000001',V='30000000-0000-4000-8000-000000000002',R='30000000-0000-4000-8000-000000000003';
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);
for(const f of ['20260910130000_platform_core.sql','../seed.sql','20260910170000_discovery.sql','20260912120000_research.sql','20260912123000_story_pitches.sql','20260912130000_editorial.sql','20260912143000_publishing.sql'])await db.exec(await readFile('supabase/migrations/'+f,'utf8'));
await db.exec(`insert into auth.users values('${U}'),('${V}'),('${R}');insert into workspace_members(workspace_id,user_id,role) values('${W}','${U}','owner'),('${W}','${V}','viewer'),('${W}','${R}','reviewer');set role authenticated;select set_config('request.jwt.claim.sub','${U}',false)`);
const group=(await db.query(`insert into story_groups(workspace_id,title) values('${W}','Test group') returning id`)).rows[0].id;
const story=(await db.query(`insert into incoming_stories(workspace_id,title,original_text,original_payload,fingerprint,intake_kind) values('${W}','Original','Original','{}','editorial-test','tip') returning id`)).rows[0].id;
await db.exec(`insert into story_group_items(workspace_id,group_id,story_id) values('${W}','${group}','${story}');insert into story_pitches(workspace_id,story_id,headline,alternative,reader_value,reporting_questions) values('${W}','${story}','Idea','','','');update story_pitches set headline='Revised idea';`);
const claim=(await db.query(`insert into research_claims(workspace_id,group_id,claim) values('${W}','${group}','Test assertion') returning id`)).rows[0].id;
await db.exec(`insert into claim_evidence(workspace_id,claim_id,source_url,publisher,excerpt,relationship) values('${W}','${claim}','https://example.com','Test source','Test excerpt','supports')`);
await assert.rejects(db.exec(`update claim_evidence set excerpt='changed'`),e=>e.code==='42501');
const id=(await db.query(`insert into editorial_drafts(workspace_id,group_id,headline,body) values('${W}','${group}','Draft headline','Draft body') returning id`)).rows[0].id;
const update=s=>db.exec(`update editorial_drafts set ${s} where id='${id}'`);
await assert.rejects(update("status='approved'"),/Invalid editorial transition/);
await assert.rejects(update("status='in_review'"),/Complete the editorial checks/);
await update("risk_level='standard',risk_notes='Checks recorded',facts_checked=true,harm_checked=true,rights_checked=true");
await update("status='in_review'");
await assert.rejects(update("body='Unreviewed edit'"),/Reopen before editing/);
await assert.rejects(update("status='approved'"),/review note is required/);
await update("status='approved',review_notes='Reviewed evidence and wording'");
assert.equal((await db.query('select reviewed_by from editorial_drafts')).rows[0].reviewed_by,U);
await update("status='draft'");assert.equal((await db.query('select reviewed_by from editorial_drafts')).rows[0].reviewed_by,null);
await update("risk_level='high'");await update("status='in_review'");await assert.rejects(update("status='approved',review_notes='Approve'"),/High-risk/);
await db.exec(`select set_config('request.jwt.claim.sub','${R}',false)`);await assert.rejects(update("body='Reviewer edit'"),/Only writers/);await update("status='changes_requested',review_notes='Needs specialist advice'");
await db.exec(`select set_config('request.jwt.claim.sub','${V}',false)`);assert.equal((await db.query("update editorial_drafts set status='draft' returning id")).rows.length,0);await assert.rejects(db.exec(`insert into story_groups(workspace_id,title) values('${W}','Forbidden')`),e=>e.code==='42501');
await db.exec("select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000001',false)");for(const t of ['story_groups','research_claims','claim_evidence','story_pitches','editorial_drafts'])assert.equal((await db.query('select * from '+t)).rows.length,0);
await db.exec('reset role');assert.ok((await db.query("select count(*)::int n from audit_events where entity_table='editorial_drafts'")).rows[0].n>=8);
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${U}',false)`);
await update("status='draft'");await update("risk_level='standard'");await update("status='in_review'");await update("status='approved',review_notes='Checked for delivery'");
const rev=(await db.query('select revision from editorial_drafts')).rows[0].revision;
await assert.rejects(db.query(`select public.reserve_wordpress_delivery('${id}',${rev-1},'send')`),/exact revision/);
await db.exec(`select set_config('request.jwt.claim.sub','${R}',false)`);await assert.rejects(db.query(`select public.reserve_wordpress_delivery('${id}',${rev},'send')`),/Owner access/);
await db.exec(`select set_config('request.jwt.claim.sub','${U}',false)`);
const delivery=(await db.query(`select (public.reserve_wordpress_delivery('${id}',${rev},'send')).id`)).rows[0].id;
await assert.rejects(update("status='draft'"),/transfer is active/);
await assert.rejects(db.query(`select public.reserve_wordpress_delivery('${id}',${rev},'send')`),e=>e.code==='23505');
await assert.rejects(db.exec("update wordpress_deliveries set state='publish'"),e=>e.code==='42501');
await db.exec(`select public.finish_wordpress_delivery('${delivery}','draft',42,'https://news.example/?p=42','draft','Created');`);
await db.query(`select public.reserve_wordpress_delivery('${id}',${rev},'publish')`);
await assert.rejects(db.query(`select public.reserve_wordpress_delivery('${id}',${rev},'publish')`),/matching WordPress draft/);
await db.exec(`select public.finish_wordpress_delivery('${delivery}','publish',42,'https://news.example/?p=42','publish','Published');`);
assert.equal((await db.query('select state from wordpress_deliveries')).rows[0].state,'publish');
await update("status='draft'");
await assert.rejects(db.query(`select public.reserve_wordpress_delivery('${id}',${rev},'publish')`),/exact revision/);
await db.exec("select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000001',false)");assert.equal((await db.query('select * from wordpress_deliveries')).rows.length,0);
console.log('Publishing database checks passed: owner-only sends, approved revisions, duplicate prevention, transfer locks and workspace isolation.');await db.close();
