'use client';
import {useEffect,useState} from 'react';
import {publishApprovedDraft} from '@/lib/editorial/publish';
import {articleWordCount,articleLengthError} from '@/lib/editorial/article';
import NewsroomNavigation from '@/components/newsroom/navigation';
import {suggestedEditorialRisk} from '@/lib/editorial/risk';
type Draft={published_url:string|null;id:string;group_id:string;headline:string;body:string;risk_level:string;risk_notes:string;facts_checked:boolean;harm_checked:boolean;rights_checked:boolean;status:string;review_notes:string;revision:number;reviewed_by:string|null;reviewed_at:string|null};
function ArticleBody({body}:{body:string}){
 const [text,setText]=useState(body);
 const words=articleWordCount(text);
 return <label>Article draft<textarea name="body" value={text} onChange={e=>setText(e.target.value)} rows={18} maxLength={100000} aria-describedby="article-word-count"/><small id="article-word-count" className="block mb-4">{words.toLocaleString('en-GB')} {words===1?'word':'words'} · {words<400?`Incomplete — ${400-words} more words required`:'Minimum length met'} (source links excluded)</small></label>;
}
export default function Editorial(){
 const [drafts,setDrafts]=useState<Draft[]>([]),[groups,setGroups]=useState<{id:string;title:string}[]>([]),[role,setRole]=useState(''),[selected,setSelected]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[targetGroup,setTargetGroup]=useState('');
 async function load(){try{const [a,b]=await Promise.all([fetch('/api/editorial',{cache:'no-store'}),fetch('/api/research',{cache:'no-store'})]);const x=await a.json() as {drafts:Draft[];role:string;error?:string},y=await b.json() as {groups:{id:string;title:string}[];error?:string};if(!a.ok||!b.ok)throw Error(x.error||y.error);setDrafts(x.drafts);setGroups(y.groups);setRole(x.role);const wanted=new URLSearchParams(window.location.search).get('group')||'';setTargetGroup(wanted);const wantedDraft=new URLSearchParams(window.location.search).get('draft');setSelected(old=>old||x.drafts.find(d=>d.id===wantedDraft)?.id||x.drafts.find(d=>d.group_id===wanted)?.id||x.drafts.find(d=>!d.published_url)?.id||'');setLoaded(true);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load editorial desk.');}}
 useEffect(()=>{void load();},[]);
 async function act(values:Record<string,unknown>,submitAfterSave=false,publishAfterReview=false){setBusy(true);setMessage('Saving…');try{
 const send=async(payload:Record<string,unknown>)=>{const r=await fetch('/api/editorial',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json() as {id?:string;revision?:number;message:string;error?:string};if(!r.ok)throw Error(data.error||'Could not save.');return data;};
 let data=await send(values);
 if(submitAfterSave){setMessage('Draft saved. Submitting for review…');try{data=await send({action:'transition',id:data.id,revision:data.revision,status:'in_review'});}catch(e){await load();throw Error('Your draft was saved, but review submission failed: '+(e instanceof Error?e.message:'Please retry.'));}}
 if(publishAfterReview){setMessage('Saving your approval…');data=await send({action:'transition',id:data.id,revision:data.revision,status:'approved',review_notes:'Owner approved the editorial checks and selected Publish to WordPress from the draft page.'});setMessage('Publishing to WordPress…');data.message=await publishApprovedDraft(data.id!,data.revision!);}
 setMessage(data.message);await load();if(data.id)setSelected(data.id);
 }catch(e){setMessage(e instanceof Error?e.message:'Could not save.');await load();}finally{setBusy(false);}}

 const d=drafts.find(x=>x.id===selected),writer=['owner','editor'].includes(role),reviewer=['owner','reviewer'].includes(role),editable=d&&!d.published_url&&writer&&['draft','changes_requested'].includes(d.status);
 return <><NewsroomNavigation active="drafts"/><main className="desk editorial-page"><h1>Drafts</h1><p>Finish your article, check it, then publish. Articles need at least 400 words.</p><button disabled={busy} onClick={()=>void load()}>Refresh drafts</button>{!loaded&&!message&&<p>Loading drafts…</p>}
 <div className="desk-columns"><aside><h2>In progress</h2>{drafts.filter(x=>!x.published_url).map(x=><button className="draft-choice" key={x.id} aria-pressed={x.id===selected} onClick={()=>setSelected(x.id)}>{x.headline}<small>{articleWordCount(x.body)} words · {articleWordCount(x.body)<400?'Needs writing':x.status==='approved'?'Ready to publish':x.status.replaceAll('_',' ')}</small></button>)}{loaded&&!drafts.some(x=>!x.published_url)&&<p>No unfinished drafts. <a href="/live">Choose your next story →</a></p>}{writer&&<details className="mt-6"><summary>Start a draft manually</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act({action:'create',group_id:f.get('group_id'),headline:f.get('headline')});}}><h3>Start writing</h3><label>Shortlisted story<select name="group_id" required value={targetGroup} onChange={e=>setTargetGroup(e.target.value)}><option value="" disabled>Choose a story</option>{groups.map(g=><option value={g.id} key={g.id}>{g.title}</option>)}</select></label><label>Working headline<input key={targetGroup} name="headline" defaultValue={groups.find(g=>g.id===targetGroup)?.title??''} required maxLength={500}/></label><button disabled={busy||!groups.length}>Create draft</button></form></details>}</aside>
 <section>{!d?<div className="panel"><h2>{targetGroup?'Your story is ready to draft':'Choose a story to continue'}</h2><p>{targetGroup?'Your story and headline are selected. Click Create draft to open the editor.':'Open an unfinished draft from the list, or choose your next story from Stories.'}</p><p>Next: review the article and complete the checks, then use Save and publish to WordPress.</p></div>:<div key={d.id+':'+d.revision}><h2>{d.headline}</h2>{d.published_url?<div className="note"><strong>Published on WordPress</strong><p><a href={d.published_url} target="_blank" rel="noreferrer">View live article ↗</a> · <a href="/live">Choose next story →</a></p></div>:articleWordCount(d.body)<400?<p className="note">Incomplete source draft. Develop this to at least 400 words before publishing. Automatic writing is currently paused.</p>:<p className="note">Minimum length met. Review the content and your checks before publishing.</p>}<details className="my-4"><summary>Sources & research</summary><a href={'/research?group='+encodeURIComponent(d.group_id)}>Open evidence and research notes →</a></details><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const intent=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value');const publish=intent==='publish';const submit=intent==='submit'||publish;if(submit){const missing=[];const lengthError=articleLengthError(String(f.get('body')||''));if(lengthError)missing.push(lengthError);if(f.get('risk_level')==='unassessed')missing.push('choose an editorial risk level');if(!String(f.get('risk_notes')||'').trim())missing.push('add risk assessment notes');if(!f.has('editorial_checks'))missing.push('complete the editorial checkbox');if(missing.length){setMessage('Before submitting: '+missing.join('; ')+'. Your entries are still here.');return;}}void act({action:'save',id:d.id,revision:d.revision,headline:f.get('headline'),body:f.get('body'),risk_level:f.get('risk_level'),risk_notes:f.get('risk_notes'),facts_checked:f.has('editorial_checks'),harm_checked:f.has('editorial_checks'),rights_checked:f.has('editorial_checks')},submit,publish);}}>
 <fieldset disabled={!editable||busy}><label>Headline<input name="headline" defaultValue={d.headline} required maxLength={500}/></label><ArticleBody body={d.body}/><div className="note"><strong>Artwork</strong><p>AI artwork is paused to avoid API charges during testing. Publishing now sends a text-only article.</p></div><label>Editorial risk<select name="risk_level" defaultValue={d.risk_level==='unassessed'?suggestedEditorialRisk(d.headline+' ' +d.body):d.risk_level}><option value="unassessed">Not assessed</option><option value="standard">Standard</option><option value="sensitive">Sensitive — explain the safeguards</option><option value="high">High — approval blocked pending specialist clearance</option></select><small className="block mb-4">{d.risk_level==='unassessed'?'Suggested from the story. Change it if needed before confirming your checks.':'Your saved assessment. Change it if needed.'}</small></label><label>Risk assessment and safeguards<textarea name="risk_notes" defaultValue={d.risk_notes} rows={4} maxLength={4000}/></label><label className="check-row"><input type="checkbox" name="editorial_checks" defaultChecked={d.facts_checked&&d.harm_checked&&d.rights_checked}/>I’ve checked the facts, potential harm and privacy, attribution, and rights to the material.</label>{editable&&<div><button type="submit" value="save" disabled={busy}>Save draft</button> {role==='owner'?<button type="submit" value="publish" disabled={busy}>{busy?'Working…':'Save and publish to WordPress →'}</button>:<button type="submit" value="submit" disabled={busy}>{busy?'Saving…':'Save and submit for review →'}</button>}<p>{role==='owner'?'Publish saves your changes, records your approval and makes this article public on WordPress.':'Save and submit includes all changes you’ve just made.'}</p></div>}</fieldset></form>
 {writer&&!d.published_url&&d.status!=='draft'&&<p><button disabled={busy} onClick={()=>void act({action:'transition',id:d.id,revision:d.revision,status:'draft'})}>Reopen as draft</button><small> Reopening clears the previous approval. Submit again after editing.</small></p>}
 {d.status==='in_review'&&reviewer&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act({action:'transition',id:d.id,revision:d.revision,status:f.get('decision'),review_notes:f.get('review_notes')});}}><h3>Review decision</h3><p>Read the draft and research before deciding. The owner can review their own draft; every decision is recorded.</p><label>Decision<select name="decision"><option value="changes_requested">Request changes</option><option value="approved" disabled={d.risk_level==='high'}>Approve editorially</option></select></label><label>Review notes<textarea name="review_notes" required maxLength={4000}/></label><button disabled={busy}>Record decision</button></form>}{d.status==='approved'&&!d.published_url&&role==='owner'&&<div className="note"><p>Approved. Publish directly or resume a confirmed WordPress draft.</p><button disabled={busy} onClick={async()=>{setBusy(true);setMessage('Publishing to WordPress…');try{setMessage(await publishApprovedDraft(d.id,d.revision));}catch(e){setMessage(e instanceof Error?e.message:'Publishing failed.');}finally{await load();setBusy(false);}}}>Publish to WordPress →</button></div>}{d.review_notes&&<details className="my-4"><summary>Review history</summary><blockquote><strong>Review notes</strong><p>{d.review_notes}</p><small>{d.reviewed_at?new Date(d.reviewed_at).toLocaleString('en-GB'):''}</small></blockquote></details>}</div>}</section></div>{message&&<div role="status" aria-live="polite" style={{position:"sticky",bottom:12,zIndex:20,padding:"16px 20px",background:"#102d61",color:"white",borderRadius:8,boxShadow:"0 4px 16px #0003"}}>{message}</div>}</main></>;
}
