'use client';
import {useEffect,useState} from 'react';
type Draft={id:string;group_id:string;headline:string;body:string;risk_level:string;risk_notes:string;facts_checked:boolean;harm_checked:boolean;rights_checked:boolean;status:string;review_notes:string;revision:number;reviewed_by:string|null;reviewed_at:string|null};
export default function Editorial(){
 const [drafts,setDrafts]=useState<Draft[]>([]),[groups,setGroups]=useState<{id:string;title:string}[]>([]),[role,setRole]=useState(''),[selected,setSelected]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 async function load(){try{const [a,b]=await Promise.all([fetch('/api/editorial',{cache:'no-store'}),fetch('/api/research',{cache:'no-store'})]);const x=await a.json() as {drafts:Draft[];role:string;error?:string},y=await b.json() as {groups:{id:string;title:string}[];error?:string};if(!a.ok||!b.ok)throw Error(x.error||y.error);setDrafts(x.drafts);setGroups(y.groups);setRole(x.role);setLoaded(true);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load editorial desk.');}}
 useEffect(()=>{void load();},[]);
 async function act(values:Record<string,unknown>){setBusy(true);setMessage('');try{const r=await fetch('/api/editorial',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});const data=await r.json() as {id?:string;message:string;error?:string};if(!r.ok)throw Error(data.error);setMessage(data.message);await load();if(data.id)setSelected(data.id);}catch(e){setMessage(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 const d=drafts.find(x=>x.id===selected),writer=['owner','editor'].includes(role),reviewer=['owner','reviewer'].includes(role),editable=d&&writer&&['draft','changes_requested'].includes(d.status);
 return <><header className="masthead"><a className="brand" href="/live">TODAY<span>UK</span></a><a href="/live">← Incoming stories</a></header><main className="desk editorial-page"><p className="eyebrow">EDITORIAL DESK</p><h1>Drafts & review</h1><p>Develop the story, record your checks, then request an editorial decision. Approval here does not publish anything.</p><p><a href="/research">Open research desk →</a></p><button disabled={busy} onClick={()=>void load()}>Refresh drafts</button>{message&&<p role="status">{message}</p>}{!loaded&&!message&&<p>Loading drafts…</p>}
 <div className="desk-columns"><aside><h2>Stories in progress</h2>{drafts.map(x=><button className="draft-choice" key={x.id} aria-pressed={x.id===selected} onClick={()=>setSelected(x.id)}>{x.headline}<small>{x.status.replaceAll('_',' ')} · revision {x.revision}</small></button>)}{loaded&&!drafts.length&&<p>No drafts yet. Create a research group, then start a draft below.</p>}{writer&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act({action:'create',group_id:f.get('group_id'),headline:f.get('headline')});}}><h3>Start a draft</h3><label>Research group<select name="group_id" required defaultValue=""><option value="" disabled>Choose a group</option>{groups.map(g=><option value={g.id} key={g.id}>{g.title}</option>)}</select></label><label>Working headline<input name="headline" required maxLength={500}/></label><button disabled={busy||!groups.length}>Create draft</button></form>}</aside>
 <section>{!d?<p>Select a draft to write or review it.</p>:<div key={d.id+':'+d.revision}><h2>{d.headline}</h2><p><strong>{d.status.replaceAll('_',' ')}</strong> · Revision {d.revision}</p><p><a href={'/research?group='+encodeURIComponent(d.group_id)}>Review the linked sources and evidence →</a></p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act({action:'save',id:d.id,revision:d.revision,headline:f.get('headline'),body:f.get('body'),risk_level:f.get('risk_level'),risk_notes:f.get('risk_notes'),facts_checked:f.has('facts_checked'),harm_checked:f.has('harm_checked'),rights_checked:f.has('rights_checked')});}}>
 <fieldset disabled={!editable||busy}><label>Headline<input name="headline" defaultValue={d.headline} required maxLength={500}/></label><label>Article draft<textarea name="body" defaultValue={d.body} rows={18} maxLength={100000}/></label><label>Editorial risk<select name="risk_level" defaultValue={d.risk_level}><option value="unassessed">Not assessed</option><option value="standard">Standard</option><option value="sensitive">Sensitive — explain the safeguards</option><option value="high">High — approval blocked pending specialist clearance</option></select></label><label>Risk assessment and safeguards<textarea name="risk_notes" defaultValue={d.risk_notes} rows={4} maxLength={4000}/></label><label className="check-row"><input type="checkbox" name="facts_checked" defaultChecked={d.facts_checked}/>I checked the facts against the evidence and addressed contradictions.</label><label className="check-row"><input type="checkbox" name="harm_checked" defaultChecked={d.harm_checked}/>I assessed potential harm, privacy, allegations and vulnerable people.</label><label className="check-row"><input type="checkbox" name="rights_checked" defaultChecked={d.rights_checked}/>I checked attribution and rights to the material used.</label>{editable&&<button disabled={busy}>Save draft and checks</button>}</fieldset></form>
 {editable&&<p><button disabled={busy} onClick={()=>void act({action:'transition',id:d.id,revision:d.revision,status:'in_review'})}>Submit saved draft for review</button></p>}{writer&&d.status!=='draft'&&<p><button disabled={busy} onClick={()=>void act({action:'transition',id:d.id,revision:d.revision,status:'draft'})}>Reopen as draft</button><small> Reopening clears the previous approval. Submit again after editing.</small></p>}
 {d.status==='in_review'&&reviewer&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act({action:'transition',id:d.id,revision:d.revision,status:f.get('decision'),review_notes:f.get('review_notes')});}}><h3>Review decision</h3><p>Read the draft and research before deciding. The owner can review their own draft; every decision is recorded.</p><label>Decision<select name="decision"><option value="changes_requested">Request changes</option><option value="approved" disabled={d.risk_level==='high'}>Approve editorially</option></select></label><label>Review notes<textarea name="review_notes" required maxLength={4000}/></label><button disabled={busy}>Record decision</button></form>}{d.review_notes&&<blockquote><strong>Review notes</strong><p>{d.review_notes}</p><small>{d.reviewed_at?new Date(d.reviewed_at).toLocaleString('en-GB'):''}</small></blockquote>}</div>}</section></div></main></>;
}
