import {newsroomClient} from '@/lib/supabase/server';
import {WordPressClient,wordpressConfig} from '@/lib/wordpress/client';
import {fingerprint,matches,monitorMessage} from '@/lib/content/monitor';
import {articleLengthError} from '@/lib/editorial/article';
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store'}});
async function context(){const db=await newsroomClient();if(!db)return null;const {data:{user}}=await db.auth.getUser();if(!user)return null;const {data:w}=await db.from('workspaces').select('id').eq('slug','todayuk').single();if(!w)return null;const {data:m}=await db.from('workspace_members').select('role').eq('workspace_id',w.id).eq('user_id',user.id).single();return m?{db,w,role:m.role}:null;}
export async function GET(){const c=await context();if(!c)return reply({error:'Sign in to the newsroom.'},401);const [d,m,f]=await Promise.all([c.db.from('wordpress_deliveries').select('*').eq('workspace_id',c.w.id).eq('state','publish').order('created_at',{ascending:false}).limit(200),c.db.from('content_management').select('*').eq('workspace_id',c.w.id),c.db.from('content_followups').select('*').eq('workspace_id',c.w.id).order('due_at')]);if(d.error||m.error||f.error)return reply({error:'Content management is unavailable. Please retry.'},503);const drafts=await c.db.from('editorial_drafts').select('id,group_id').eq('workspace_id',c.w.id);if(drafts.error)return reply({error:'Source links could not be loaded.'},503);return reply({role:c.role,articles:d.data.map(a=>({...a,group_id:drafts.data.find(x=>x.id===a.draft_id)?.group_id,management:m.data.find(x=>x.delivery_id===a.id)??null,followups:f.data.filter(x=>x.delivery_id===a.id)}))});}
export async function POST(request:Request){if(request.headers.get('origin')!=='https://todayuk-newsroom.digitalunicorn.chatgpt.site')return reply({error:'Request origin not allowed.'},403);const c=await context();if(!c)return reply({error:'Sign in to the newsroom.'},401);try{const raw=await request.text();if(raw.length>120000)return reply({error:'Article too large.'},413);const b=JSON.parse(raw);const {data:d,error}=await c.db.from('wordpress_deliveries').select('*').eq('workspace_id',c.w.id).eq('id',b.id).eq('state','publish').single();if(error||!d)return reply({error:'Published article not found.'},404);
if(b.action==='followup'||b.action==='complete'){if(!['owner','editor'].includes(c.role))return reply({error:'Editor access required.'},403);let r;if(b.action==='followup'){const due=new Date(b.due_at);if(!String(b.task??'').trim()||!Number.isFinite(due.getTime()))return reply({error:'Enter a task and valid date.'},400);r=await c.db.from('content_followups').insert({workspace_id:c.w.id,delivery_id:d.id,task:String(b.task).trim(),due_at:due.toISOString()});}else r=await c.db.from('content_followups').update({completed:b.completed===true}).eq('workspace_id',c.w.id).eq('delivery_id',d.id).eq('id',b.followup_id).select('id').single();if(r.error)throw Error('Could not save the follow-up.');return reply({message:'Follow-up saved.'});}
if(c.role!=='owner')return reply({error:'Owner access required for WordPress actions.'},403);const config=wordpressConfig();if(!config)throw Error('WordPress connection needs attention.');const wp=new WordPressClient(config);const {data:m,error:me}=await c.db.from('content_management').select('*').eq('workspace_id',c.w.id).eq('delivery_id',d.id).maybeSingle();if(me)throw Error('Could not load article state.');
const rpc=async(action:string,values:Record<string,unknown>)=>{const r=await c.db.rpc('content_manage',{p_delivery:d.id,p_action:action,p_values:values});if(r.error)throw Error('The article changed or an update is unresolved. Refresh and check its status.');return r.data;};
if(!['check','update','reconcile','accept'].includes(b.action))return reply({error:'Unknown action.'},400);
const remote=await wp.read(d.wordpress_id),hash=await fingerprint(remote);
if(b.action==='check'||b.action==='accept'){if(b.action==='accept'&&!b.confirmed)return reply({error:'Confirm you reviewed the live changes.'},400);const message=b.action==='accept'?'Live changes reviewed. Saved text retained.':!m?.remote_fingerprint&&!matches(remote,d.headline,d.body)?'Changed in WordPress. Review the live article before updating.':m?.check_message?.startsWith('Changed in WordPress')&&hash===m.remote_fingerprint?m.check_message:monitorMessage(remote,hash,m?.remote_fingerprint??null);await rpc('check',{fingerprint:hash,modified:remote.modified_gmt,status:remote.status,message,accept:b.action==='accept'});return reply({message:b.action==='accept'?'Live changes acknowledged. Your saved article is retained; review differences before replacing it.':message});}
if(b.action==='reconcile'){const applied=!!m?.pending_headline&&matches(remote,m.pending_headline,m.pending_body),unchanged=hash===m?.remote_fingerprint;if(!applied&&!unchanged)return reply({error:'WordPress differs from both versions. Review it manually; no automatic overwrite was made.'},409);await rpc('reconcile',{applied,fingerprint:hash,modified:remote.modified_gmt,status:remote.status,message:applied?'The update was confirmed on WordPress.':'WordPress is unchanged. It is safe to try the update again.'});return reply({message:'Update reconciled. No new post was created.'});}
if(!m?.remote_fingerprint)return reply({error:'Check the live article before its first update.'},409);if(remote.status!=='publish'||hash!==m.remote_fingerprint||m.check_message?.startsWith('Changed in WordPress'))return reply({error:'The live article changed. Check it and review changes before updating.'},409);const headline=String(b.headline??'').trim(),body=String(b.body??'');const lengthError=articleLengthError(body);if(lengthError)return reply({error:lengthError},409);if(!headline||headline.length>500||!b.checks||!['standard','sensitive'].includes(b.risk)||!String(b.notes??'').trim())return reply({error:'Complete the article, risk notes and editorial check.'},400);
const reserved=await rpc('reserve',{version:b.version,fingerprint:hash,headline,body,checks:true,risk:b.risk,notes:b.notes});
try{const latest=await wp.read(d.wordpress_id);if(await fingerprint(latest)!==hash){await rpc('cancel',{operation:reserved.operation});return reply({error:'WordPress changed during editing. Your update was not sent.'},409);}await wp.update(d.wordpress_id,headline,body);const confirmed=await wp.read(d.wordpress_id);if(confirmed.status!=='publish'||!matches(confirmed,headline,body))throw Error('WordPress has not confirmed the exact update.');await rpc('finish',{operation:reserved.operation,fingerprint:await fingerprint(confirmed),modified:confirmed.modified_gmt,status:confirmed.status});return reply({message:'Updated the existing WordPress article. Its address is unchanged.'});}catch(e){await c.db.rpc('content_manage',{p_delivery:d.id,p_action:'uncertain',p_values:{operation:reserved.operation}});throw e;}
}catch(e){return reply({error:e instanceof Error?e.message:'Could not complete the action.'},409);}}
