import {useState} from 'react';
import {Engagement,engagementLabels,suggestEngagement} from '@/lib/editorial/engagement';
export default function EngagementEditor({saved,text}:{saved:Engagement|null;text:string}){
 const initial=saved??suggestEngagement(text);
 const [tool,setTool]=useState(initial.mode==='off'?'off':initial.tools.find(t=>t!=='share')??'helpful');
 const [question,setQuestion]=useState(initial.question),[answers,setAnswers]=useState(initial.options.join('\n')),[approved,setApproved]=useState(!!saved);
 const config={...initial,mode:tool==='off'?'off':'custom',tools:tool==='off'?[]:[tool,'share'],question,options:answers.split('\n').map(s=>s.trim()).filter(Boolean)};
 return <div className="panel my-4"><h3>Reader engagement</h3><p>{saved?'Your saved choice.':'Suggested for this story. Approve it here and it will appear with the published article.'}</p><input type="hidden" name="engagement" value={JSON.stringify(config)}/><label>Tool<select value={tool} onChange={e=>{setTool(e.target.value);setApproved(false);}}>{Object.entries(engagementLabels).map(([id,label])=><option value={id} key={id}>{label}</option>)}<option value="off">No engagement on this article</option></select></label>{tool==='poll'?<><label>Poll question<input maxLength={180} value={question} onChange={e=>{setQuestion(e.target.value);setApproved(false);}}/></label><label>Answer choices — one per line<textarea rows={4} value={answers} onChange={e=>{setAnswers(e.target.value);setApproved(false);}}/></label></>:tool==='nimby'?<p>Readers choose: Strongly oppose · Oppose · Neutral · Support · Strongly support.</p>:tool==='attendance'?<p>Readers choose: Going · Interested · I was there.</p>:tool==='seen'?<p>Readers can select “I’ve seen this”.</p>:tool==='helpful'?<p>Readers can mark this article as helpful.</p>:<p>No reader engagement controls will be added.</p>}{tool!=='off'&&<p>Also includes Share locally.</p>}<label className="check-row"><input name="engagement_approved" type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>{tool==='off'?'Confirm no engagement for this article':'Approve this engagement for publication'}</label></div>;
}
