'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
type Group={id:string;title:string};type Story={id:string;title:string;original_url:string|null};type Claim={id:string;group_id:string;claim:string};type Evidence={id:string;claim_id:string;publisher:string;source_url:string;excerpt:string;relationship:string};
type Data={groups:Group[];links:{group_id:string;story_id:string}[];claims:Claim[];evidence:Evidence[];role:string};
export default function Research(){
 const [data,setData]=useState<Data|null>(null),[stories,setStories]=useState<Story[]>([]),[group,setGroup]=useState(''),[story,setStory]=useState(''),[relationship,setRelationship]=useState('supports'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function refresh(){const responses=await Promise.all([fetch('/api/research',{cache:'no-store'}),fetch('/api/discovery',{cache:'no-store'})]);const [r,d]=await Promise.all(responses.map(x=>x.json())) as [Data&{error?:string},{stories:Story[];error?:string}];if(!responses[0].ok||!responses[1].ok)throw new Error(r.error??d.error??'Could not load research.');setData(r);setStories(d.stories);setGroup(g=>g||r.groups.find(x=>x.id===new URLSearchParams(window.location.search).get('group'))?.id||r.groups[0]?.id||'');}
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[]);
 async function act(body:Record<string,unknown>){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error?:string;message:string;id?:string};if(!r.ok)throw new Error(d.error);await refresh();if(body.action==='group'&&d.id)setGroup(d.id);setMessage(d.message);return true;}catch(e){setError(e instanceof Error?e.message:'Please retry.');return false;}finally{setBusy(false);}}
 const canEdit=!!data&&['owner','editor','reviewer'].includes(data.role);const current=data?.groups.find(g=>g.id===group);const linked=data?.links.filter(l=>l.group_id===group).map(l=>l.story_id)??[];
 return <><header className="masthead"><a className="brand" href="/live">TODAY<span>UK</span></a><nav><a href="/live">← Incoming queue</a> · <a href="/editorial">Drafts & review →</a></nav></header><main className="desk"><div className="intro"><div><p className="eyebrow">Research desk</p><h1>Groups, claims & evidence</h1><p className="muted">Bring source reports together and record what supports or contradicts each claim.</p></div><Button variant="outline" disabled={busy} onClick={()=>refresh().catch(e=>setError(e.message))}>Refresh research</Button></div>{error&&<p role="alert" className="note">{error}</p>}{message&&<p role="status" className="note">{message}</p>}
 <div className="desk-columns"><aside className="panel"><h2>Story groups</h2>{data?.groups.map(g=><Button key={g.id} variant={group===g.id?'default':'outline'} className="w-full h-auto whitespace-normal mb-2 justify-start text-left" onClick={()=>setGroup(g.id)}>{g.title}</Button>)}{data&&!data.groups.length&&<p className="muted">No groups yet. Create one for the event you want to research.</p>}{canEdit&&<form className="mt-5" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;if(await act({action:'group',title:new FormData(form).get('title')}))form.reset();}}><label htmlFor="group-title">New group title</label><Input id="group-title" name="title" required maxLength={500} className="my-3"/><Button disabled={busy} type="submit">Create group</Button></form>}</aside>
 <div>{current?<><section className="panel"><h2>{current.title}</h2><p className="muted">Link reports only when they concern the same event. Linking does not verify their claims.</p>{linked.map(id=>{const s=stories.find(x=>x.id===id);return <div key={id} className="row"><span>{s?.title??'Linked source report'}{s?.original_url&&<a className="block text-blue-800 text-sm" href={s.original_url} target="_blank" rel="noreferrer">Open original ↗</a>}</span>{canEdit&&<Button variant="outline" disabled={busy} onClick={()=>act({action:'unlink',group_id:group,story_id:id})}>Unlink</Button>}</div>;})}{canEdit&&<div className="flex flex-wrap gap-3 mt-5"><Select value={story} onValueChange={v=>setStory(v??'')}><SelectTrigger aria-label="Story to link" className="max-w-full"><SelectValue placeholder="Choose a report from the queue"/></SelectTrigger><SelectContent>{stories.filter(s=>!linked.includes(s.id)).map(s=><SelectItem value={s.id} key={s.id}>{s.title}</SelectItem>)}</SelectContent></Select><Button disabled={busy||!story||linked.includes(story)} onClick={()=>act({action:'link',group_id:group,story_id:story})}>Link report</Button></div>}</section>
 <section className="panel mt-5"><h2>Claims to check</h2><p className="muted mb-5">Evidence is an editorial record, not an automated fact verdict. Different links may repeat the same source; check independence yourself.</p>{data?.claims.filter(c=>c.group_id===group).map(c=>{const evidence=data.evidence.filter(e=>e.claim_id===c.id);const publishers=new Set(evidence.filter(e=>e.relationship==='supports').map(e=>e.publisher.trim().toLowerCase()));return <article key={c.id} className="border-t pt-5 mt-5"><h3 className="text-lg font-semibold">{c.claim}</h3><p className="pill inline-block my-3">{publishers.size<2?'Second source needed':'Multiple publishers recorded · check independence'}{evidence.some(e=>e.relationship==='contradicts')?' · Conflicting evidence':''}</p>{evidence.map(e=><blockquote className="note" key={e.id}><p><strong>{e.publisher}</strong> · {e.relationship}</p><p className="whitespace-pre-wrap">{e.excerpt}</p><a className="text-blue-800 underline break-all" target="_blank" rel="noreferrer" href={e.source_url}>Open evidence source ↗</a></blockquote>)}{canEdit&&<details className="mt-4"><summary className="cursor-pointer font-semibold">Add evidence</summary><form className="mt-4" onSubmit={async event=>{event.preventDefault();const form=event.currentTarget;const f=new FormData(form);if(await act({action:'evidence',claim_id:c.id,publisher:f.get('publisher'),source_url:f.get('url'),excerpt:f.get('excerpt'),relationship}))form.reset();}}><label>Publisher / organisation<Input name="publisher" required maxLength={200} className="my-2 mb-3"/></label><label>Evidence URL<Input name="url" type="url" required className="my-2 mb-3"/></label><label>Supporting passage or observation<Textarea name="excerpt" required maxLength={10000} className="my-2 mb-3"/></label><Select value={relationship} onValueChange={v=>v&&setRelationship(v)}><SelectTrigger aria-label="Evidence relationship"><SelectValue/></SelectTrigger><SelectContent>{['supports','contradicts','context'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Button disabled={busy} type="submit" className="mt-3">Save evidence</Button></form></details>}</article>;})}{canEdit&&<form className="mt-6 border-t pt-5" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;if(await act({action:'claim',group_id:group,claim:new FormData(form).get('claim')}))form.reset();}}><label htmlFor="claim">Add a factual claim to check</label><Textarea id="claim" name="claim" required maxLength={4000} className="my-3"/><Button disabled={busy} type="submit">Add claim</Button></form>}</section></>:<section className="panel"><h2>Select or create a story group</h2><p>Start with an event from the incoming queue, link the relevant reports, then record claims and evidence.</p></section>}</div></div></main></>;
}
