begin;
create table public.story_pitches (
 workspace_id uuid not null references public.workspaces(id),story_id uuid not null,
 headline text not null check(length(headline) between 1 and 500),alternative text not null check(length(alternative)<=500),
 reader_value text not null check(length(reader_value)<=2000),reporting_questions text not null check(length(reporting_questions)<=4000),
 created_at timestamptz not null default now(),primary key(workspace_id,story_id),
 foreign key(workspace_id,story_id) references public.incoming_stories(workspace_id,id)
);
alter table public.story_pitches enable row level security;
revoke all on public.story_pitches from public,anon,authenticated;
grant select,insert on public.story_pitches to authenticated;
grant update(headline,alternative,reader_value,reporting_questions) on public.story_pitches to authenticated;
create policy member_read on public.story_pitches for select to authenticated using(newsroom_private.has_role(workspace_id,array['owner','editor','reviewer','viewer']));
create policy editor_insert on public.story_pitches for insert to authenticated with check(newsroom_private.has_role(workspace_id,array['owner','editor','reviewer']));
create policy editor_update on public.story_pitches for update to authenticated using(newsroom_private.has_role(workspace_id,array['owner','editor','reviewer'])) with check(newsroom_private.has_role(workspace_id,array['owner','editor','reviewer']));
create trigger audit_changes after insert or update on public.story_pitches for each row execute function newsroom_private.audit_change();
insert into public.story_pitches(workspace_id,story_id,headline,alternative,reader_value,reporting_questions) select workspace_id,id,'Zodiac House evacuated after power outage','Power failure forces residents out of Zodiac House','A clear local incident with direct consequences for residents.','Check whether residents have returned, how many were affected, and what caused the outage.' from public.incoming_stories where original_url='https://news.croydon.gov.uk/power-outage-at-zodiac-house/' and workspace_id=(select id from public.workspaces where slug='todayuk');
insert into public.story_pitches(workspace_id,story_id,headline,alternative,reader_value,reporting_questions) select workspace_id,id,'Croydon Harvest returns on 3–4 October with music and family activities','A weekend of music and outdoor arts is coming to Croydon town centre','Useful advance information for families planning a local day out.','Confirm locations, timings, prices, accessibility and weather arrangements.' from public.incoming_stories where original_url='https://news.croydon.gov.uk/croydon-harvest-brings-folk-farmyard-and-fun-to-the-town-centre/' and workspace_id=(select id from public.workspaces where slug='todayuk');
insert into public.story_pitches(workspace_id,story_id,headline,alternative,reader_value,reporting_questions) select workspace_id,id,'Croydon plans updated levy on new developments','New development levy planned to fund Croydon infrastructure','A potentially important local money story if the changes and beneficiaries are made clear.','Find the proposed rates, adoption date, areas affected and how the money will be allocated.' from public.incoming_stories where original_url='https://news.croydon.gov.uk/croydon-moves-forward-with-updated-community-infrastructure-levy/' and workspace_id=(select id from public.workspaces where slug='todayuk');
insert into public.story_pitches(workspace_id,story_id,headline,alternative,reader_value,reporting_questions) select workspace_id,id,'Alison Johnson to lead £20m programme around Croydon University Hospital','New leader named for £20m neighbourhood programme in Croydon','A substantial neighbourhood investment story with identifiable local beneficiaries.','Confirm the funding timetable, exact boundaries, decision-making powers and how residents can influence spending.' from public.incoming_stories where original_url='https://news.croydon.gov.uk/community-leader-appointed-to-lead-20m-pride-in-place-programme/' and workspace_id=(select id from public.workspaces where slug='todayuk');
insert into public.story_pitches(workspace_id,story_id,headline,alternative,reader_value,reporting_questions) select workspace_id,id,'Croydon signs contract for three older people’s care homes','Three Croydon care homes covered by Eleanor Healthcare contract','A service-change story that could matter to residents, families and care staff.','Identify the homes, contract length and value, and what changes for residents. Seek a family or resident perspective.' from public.incoming_stories where original_url='https://news.croydon.gov.uk/improved-care-home-contract-helps-croydon-prepare-for-the-future-and-support-residents-to-live-independently-for-longer/' and workspace_id=(select id from public.workspaces where slug='todayuk');
insert into public.story_pitches(workspace_id,story_id,headline,alternative,reader_value,reporting_questions) select workspace_id,id,'School visits and town patrols support Croydon pupils as term starts','Croydon partners step up school safety advice for the new term','A practical schools story if it provides specific advice or details parents can use.','Check which schools and locations are involved, when patrols run and what advice is being offered.' from public.incoming_stories where original_url='https://news.croydon.gov.uk/back-to-school-keeping-our-young-people-safe/' and workspace_id=(select id from public.workspaces where slug='todayuk');
insert into public.story_pitches(workspace_id,story_id,headline,alternative,reader_value,reporting_questions) select workspace_id,id,'Croydon launches youth programme on council budgets and elections','P4YE to deliver Croydon’s new Youth Voice Programme','A participation story with a useful angle if young people can find out how to join.','Confirm ages, sign-up details, dates and what influence participants will actually have.' from public.incoming_stories where original_url='https://news.croydon.gov.uk/croydon-commissions-p4ye-to-deliver-a-new-youth-voice-programme/' and workspace_id=(select id from public.workspaces where slug='todayuk');
insert into public.story_pitches(workspace_id,story_id,headline,alternative,reader_value,reporting_questions) select workspace_id,id,'Green Belt and school return feature in Perry’s weekly update','Perry’s weekly update covers schools, Green Belt and CALAT','A round-up rather than a clear standalone news development; look for a specific decision to follow up.','Separate announcements from commentary and verify any claimed policy changes independently.' from public.incoming_stories where original_url='https://news.croydon.gov.uk/mayor-perry-listening-to-croydon-4-september-2026/' and workspace_id=(select id from public.workspaces where slug='todayuk');
insert into public.story_pitches(workspace_id,story_id,headline,alternative,reader_value,reporting_questions) select workspace_id,id,'Community organisations feature in Perry’s Croydon round-up','Perry reports on meetings with residents and local groups','Potential leads may sit inside the round-up, but the supplied summary offers no clear new development.','Identify named groups and any concrete decisions or changes before commissioning a full story.' from public.incoming_stories where original_url='https://news.croydon.gov.uk/mayor-perry-listening-to-croydon-28-august-2026/' and workspace_id=(select id from public.workspaces where slug='todayuk');
insert into public.story_pitches(workspace_id,story_id,headline,alternative,reader_value,reporting_questions) select workspace_id,id,'Perry reflects on first 100 days and GCSE results in weekly update','First 100 days and local communities feature in mayor’s round-up','A possible accountability angle if specific pledges and outcomes can be checked.','Compare named pledges with evidence; distinguish the mayor’s assessment from independently established results.' from public.incoming_stories where original_url='https://news.croydon.gov.uk/mayor-perry-listening-to-croydon-21-august-2026/' and workspace_id=(select id from public.workspaces where slug='todayuk');
insert into newsroom_private.applied_migrations(version) values('20260912123000_story_pitches');
commit;
