<?php
if(!defined('ABSPATH'))exit;
require_once __DIR__.'/community-model.php';
function tuc_url($page='local'){return add_query_arg('todayuk',$page,home_url('/'));}
function tuc_audit($id,$action){add_post_meta($id,'_tuc_audit',array('at'=>gmdate('c'),'user'=>get_current_user_id(),'action'=>$action));}
add_action('init',function(){
 register_post_type('tuc_tip',array('label'=>'Reader submissions','public'=>false,'show_ui'=>false,'supports'=>array('title','editor','revisions')));
 register_post_type('tuc_quiz',array('label'=>'Weekly quizzes','public'=>false,'show_ui'=>false,'supports'=>array('title')));
});
add_action('admin_init',function(){
 if(get_option('tuc_schema')==='1')return;global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$t=$wpdb->prefix.'todayuk_quiz_entries';$c=$wpdb->get_charset_collate();
 dbDelta("CREATE TABLE $t (id bigint unsigned NOT NULL AUTO_INCREMENT, quiz_id bigint unsigned NOT NULL, user_id bigint unsigned NOT NULL, area varchar(10) NOT NULL, score int NOT NULL, entered_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY entry (quiz_id,user_id)) $c;");
 if($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$t))===$t)update_option('tuc_schema','1');
});
add_action('wp_body_open',function(){echo '<nav class="tur-account-link" aria-label="Community"><a href="'.esc_url(tuc_url()).'">Local life</a> · <a href="'.esc_url(tuc_url('submit')).'">Send a story</a> · <a href="'.esc_url(tuc_url('quiz')).'">Weekly quiz</a></nav>';});
add_action('template_redirect',function(){
 if(!isset($_GET['todayuk']))return;$page=sanitize_key($_GET['todayuk']);if(!in_array($page,array('local','submit','quiz'),true))return;
 status_header(200);nocache_headers();if($page!=='local')header('X-Robots-Tag: noindex, nofollow');get_header();echo '<main id="main" class="wrap"><section class="tue tur">';
 if($page==='submit')tuc_submit_page();elseif($page==='quiz')tuc_quiz_page();else tuc_local_page();echo '</section></main>';get_footer();exit;
});
function tuc_signed_in(){if(is_user_logged_in())return true;echo '<p><a class="tur-primary" href="'.esc_url(wp_login_url(tuc_url(sanitize_key($_GET['todayuk']??'local')))).'">Sign in to take part</a> <a href="'.esc_url(tur_url()).'">Create an account</a></p>';return false;}
function tuc_verified($uid){return in_array(get_user_meta($uid,'_tur_class',true),array('community','commercial'),true)&&get_user_meta($uid,'_tuc_verified',true)==='yes';}
function tuc_submit_page(){
 echo '<h1>Send a story</h1><p>Paste a link or tell us what is happening. An editor will review it before publication. Original submissions are retained with the editorial audit trail.</p>';if(!tuc_signed_in())return;
 if(isset($_GET['sent']))echo '<p role="status">Your submission is with the editors. Track its progress below.</p>';
 echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tuc_submit">';wp_nonce_field('tuc-submit');echo '<label>Your story or link<textarea name="content" rows="7" maxlength="12000" required></textarea></label>';
 if(tuc_verified(get_current_user_id()))echo '<label>Media link (optional)<input type="url" name="media" maxlength="1000"></label><label><input type="checkbox" name="rights" value="1"> I have permission to supply this media for publication.</label><p>Share a link to permitted media. Editors check it before adding it to the article.</p>';
 echo '<button>Send to editors</button></form><h2>Your submissions</h2>';
 $tips=get_posts(array('post_type'=>'tuc_tip','post_status'=>'private','author'=>get_current_user_id(),'numberposts'=>50));if(!$tips)echo '<p>No submissions yet.</p>';
 foreach($tips as $tip)echo '<article class="tuc-card"><h3>'.esc_html($tip->post_title).'</h3><p>'.esc_html(get_post_meta($tip->ID,'_tuc_state',true)?:'Awaiting review').' · '.esc_html(get_the_date('j M Y',$tip)).'</p></article>';
}
add_action('admin_post_tuc_submit',function(){
 check_admin_referer('tuc-submit');$uid=get_current_user_id();$text=sanitize_textarea_field(wp_unslash($_POST['content']??''));if(strlen($text)<10||strlen($text)>12000)tue_notice('Add a story or link between 10 and 12,000 characters.');
 if(get_transient('tuc-rate-'.$uid))tue_notice('Please wait a minute before sending another story.');$media=esc_url_raw(wp_unslash($_POST['media']??''),array('http','https'));if($media&&(!tuc_verified($uid)||empty($_POST['rights'])))tue_notice('Media needs a verified organisation and permission to use it.');
 $id=wp_insert_post(array('post_type'=>'tuc_tip','post_status'=>'private','post_author'=>$uid,'post_title'=>wp_trim_words($text,12,'…'),'post_content'=>$text),true);if(is_wp_error($id))tue_notice('Your submission could not be saved. Please retry.');
 update_post_meta($id,'_tuc_original',$text);update_post_meta($id,'_tuc_type',tuc_detect($text));update_post_meta($id,'_tuc_media',$media);update_post_meta($id,'_tuc_verified',tuc_verified($uid)?'yes':'no');update_post_meta($id,'_tuc_state','Awaiting review');tuc_audit($id,'Submitted');set_transient('tuc-rate-'.$uid,1,60);wp_safe_redirect(add_query_arg('sent',1,tuc_url('submit')));exit;
});
add_action('admin_post_nopriv_tuc_submit',function(){auth_redirect();});
add_action('admin_menu',function(){add_submenu_page('edit.php','Reader submissions','Reader submissions','edit_others_posts','tuc-submissions','tuc_admin');add_submenu_page('edit.php','Weekly quizzes','Weekly quizzes','manage_options','tuc-quizzes','tuc_quiz_admin');});
function tuc_admin(){
 if(!current_user_can('edit_others_posts'))return;echo '<div class="wrap"><h1>Reader submissions</h1><p>Review the original, then create one editable draft. Nothing publishes automatically.</p>';
 $id=absint($_GET['tip']??0);$tip=$id?get_post($id):null;if(!$tip||$tip->post_type!=='tuc_tip'){
 $tips=get_posts(array('post_type'=>'tuc_tip','post_status'=>'private','numberposts'=>100));if(!$tips)echo '<p>No reader submissions yet.</p>';foreach($tips as $tip)echo '<p><a href="'.esc_url(add_query_arg('tip',$tip->ID,admin_url('edit.php?page=tuc-submissions'))).'">'.esc_html($tip->post_title).'</a> — '.esc_html(get_post_meta($tip->ID,'_tuc_state',true)).'</p>';echo '</div>';return;}
 $u=get_userdata($tip->post_author);echo '<h2>'.esc_html($tip->post_title).'</h2><p>From '.esc_html($u?$u->display_name:'Deleted account').'; verified organisation at submission: '.esc_html(get_post_meta($id,'_tuc_verified',true)).'.</p>';
 $history=get_posts(array('post_type'=>'tuc_tip','post_status'=>'private','author'=>$tip->post_author,'numberposts'=>100));echo '<p>Source history: '.count($history).' submissions; '.count(array_filter($history,function($p){return get_post_meta($p->ID,'_tuc_state',true)==='Draft created';})).' accepted for drafting.</p><h3>Original submission</h3><pre style="white-space:pre-wrap">'.esc_html(get_post_meta($id,'_tuc_original',true)).'</pre>';
 $media=get_post_meta($id,'_tuc_media',true);if($media)echo '<p>Supplied media: <a target="_blank" rel="noopener noreferrer" href="'.esc_url($media).'">Review media source</a> (permission declared by contributor; editorial check required).</p>';
 $draft=absint(get_post_meta($id,'_tuc_draft',true));if($draft)echo '<p><a class="button button-primary" href="'.esc_url(get_edit_post_link($draft)).'">Open article draft</a></p>';else{
 echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tuc_review"><input type="hidden" name="tip" value="'.$id.'">';wp_nonce_field('tuc-review-'.$id);echo '<p><label>Headline <input class="large-text" name="title" required value="'.esc_attr($tip->post_title).'"></label></p><p><label>Content type <select name="type">';foreach(tuc_types()as $k=>$v)echo '<option value="'.$k.'" '.selected(get_post_meta($id,'_tuc_type',true),$k,false).'>'.esc_html($v).'</option>';echo '</select></label></p><p><label>Editorial text<textarea class="large-text" name="content" rows="8">'.esc_textarea($tip->post_content).'</textarea></label></p><button class="button button-primary" name="decision" value="draft">Create article draft</button> <button class="button" name="decision" value="decline">Decline submission</button></form>';}
 echo '<h3>Audit trail</h3>';foreach(get_post_meta($id,'_tuc_audit')as $a)echo '<p>'.esc_html($a['at'].' · user '.$a['user'].' · '.$a['action']).'</p>';echo '</div>';
}
add_action('admin_post_tuc_review',function(){
 $id=absint($_POST['tip']??0);check_admin_referer('tuc-review-'.$id);$tip=get_post($id);if(!current_user_can('edit_others_posts')||!$tip||$tip->post_type!=='tuc_tip')wp_die('Not allowed.');
 $lock='tuc-review-'.$id;if(!add_option($lock,time(),'','no'))tue_notice('This submission is already being processed. Refresh before trying again.');
 if(!get_post_meta($id,'_tuc_draft',true)){
 if(($_POST['decision']??'')==='draft'){$type=sanitize_key($_POST['type']??'news');if(!isset(tuc_types()[$type]))$type='news';$draft=wp_insert_post(array('post_type'=>'post','post_status'=>'draft','post_title'=>sanitize_text_field(wp_unslash($_POST['title']??'')),'post_content'=>wp_kses_post(wp_unslash($_POST['content']??'')),'post_author'=>get_current_user_id()),true);if(is_wp_error($draft)){delete_option($lock);tue_notice('Could not create the draft.');}$cat=get_term_by('slug','cr-news','category');if($cat)wp_set_post_categories($draft,array($cat->term_id));update_post_meta($draft,'_tuc_type',$type);update_post_meta($draft,'_tuc_submission',$id);update_post_meta($id,'_tuc_draft',$draft);update_post_meta($id,'_tuc_state','Draft created');tuc_audit($id,'Created draft '.$draft);}elseif(($_POST['decision']??'')==='decline'){update_post_meta($id,'_tuc_state','Declined');tuc_audit($id,'Declined');}}
 delete_option($lock);wp_safe_redirect(add_query_arg('tip',$id,admin_url('edit.php?page=tuc-submissions')));exit;
});
function tuc_verify_field($u){if(!current_user_can('manage_options'))return;echo '<p><label><input type="checkbox" name="tuc_verified" value="yes" '.checked(get_user_meta($u->ID,'_tuc_verified',true),'yes',false).'> Organisation identity verified for permitted media submissions</label></p><p>Applies to community and commercial organisations only. All contributions still require editorial approval.</p>';}
add_action('show_user_profile','tuc_verify_field');add_action('edit_user_profile','tuc_verify_field');
function tuc_verify_save($uid){if(current_user_can('manage_options')&&current_user_can('edit_user',$uid)){update_user_meta($uid,'_tuc_verified',($_POST['tuc_verified']??'')==='yes'?'yes':'no');}}
add_action('personal_options_update','tuc_verify_save');add_action('edit_user_profile_update','tuc_verify_save');
function tuc_local_page(){
 echo '<h1>Local life</h1><p><a href="'.esc_url(tuc_url('submit')).'">Send a local story or listing</a></p><form method="get"><input type="hidden" name="todayuk" value="local"><label>Section<select name="section"><option value="">All sections</option>'; $section=sanitize_key($_GET['section']??'');foreach(tuc_types()as $k=>$v)if($k!=='news')echo '<option value="'.$k.'" '.selected($section,$k,false).'>'.esc_html($v).'</option>';echo '</select></label><button>Show listings</button></form>';
 $args=array('post_type'=>'post','post_status'=>'publish','has_password'=>false,'numberposts'=>50,'meta_query'=>array(array('key'=>'_tuc_type','value'=>$section&&isset(tuc_types()[$section])?$section:array_diff(array_keys(tuc_types()),array('news')),'compare'=>$section&&isset(tuc_types()[$section])?'=':'IN')));$posts=get_posts($args);
 if(!$posts)echo '<p>No published listings in this section yet.</p>';echo '<div class="tur-feed">';foreach($posts as $p){$m=(array)get_post_meta($p->ID,'_tuc_local',true);echo '<article><small>'.esc_html(tuc_types()[get_post_meta($p->ID,'_tuc_type',true)]??'Local').'</small><h2><a href="'.esc_url(get_permalink($p)).'">'.esc_html($p->post_title).'</a></h2><p>'.esc_html(($m['locality']??'').' '.($m['area']??'')).'</p><p>'.esc_html($m['status']??'').'</p></article>';}echo '</div>';
}
add_action('add_meta_boxes',function(){add_meta_box('tuc-local','Local listing details','tuc_local_box','post','normal','default');});
function tuc_local_box($p){$type=get_post_meta($p->ID,'_tuc_type',true)?:'news';$m=(array)get_post_meta($p->ID,'_tuc_local',true);wp_nonce_field('tuc-local','tuc_local_nonce');echo '<p>Leave News tip for a general article. Use structured details for local listings. Never include private contact or collection addresses.</p><label>Content type <select name="tuc_type">';foreach(tuc_types()as $k=>$v)echo '<option value="'.$k.'" '.selected($type,$k,false).'>'.esc_html($v).'</option>';echo '</select></label>';foreach(tuc_fields()as $k=>$label)echo '<p><label>'.esc_html($label).'<input class="widefat" name="tuc_local['.$k.']" type="'.(in_array($k,array('booking','source'))?'url':(in_array($k,array('start','end'))?'datetime-local':'text')).'" value="'.esc_attr($m[$k]??'').'"></label></p>';echo '<p>Examples of status: open, cancelled, found, reunited, available, reserved, collected. Competitions require their own rules and prize; they are separate from free items.</p>';}
add_action('save_post_post',function($id){
 if(wp_is_post_revision($id)||!current_user_can('edit_post',$id)||empty($_POST['tuc_local_nonce'])||!wp_verify_nonce($_POST['tuc_local_nonce'],'tuc-local'))return;$type=sanitize_key($_POST['tuc_type']??'news');if(!isset(tuc_types()[$type]))return;$m=array();$raw=wp_unslash($_POST['tuc_local']??array());foreach(tuc_fields()as $k=>$v)$m[$k]=in_array($k,array('booking','source'))?esc_url_raw($raw[$k]??'',array('http','https')):sanitize_text_field($raw[$k]??'');update_post_meta($id,'_tuc_type',$type);update_post_meta($id,'_tuc_local',$m);tuc_audit($id,'Local details updated');
});
add_filter('the_content',function($content){if(!is_singular('post')||!in_the_loop()||!is_main_query()||post_password_required())return $content;$id=get_the_ID();$type=get_post_meta($id,'_tuc_type',true);if(!$type||$type==='news')return $content;$m=(array)get_post_meta($id,'_tuc_local',true);$html='<section class="tue"><h2>Useful details</h2><dl>';foreach(tuc_fields()as $k=>$label)if(!empty($m[$k]))$html.='<dt>'.esc_html($label).'</dt><dd>'.(in_array($k,array('booking','source'))?'<a href="'.esc_url($m[$k]).'" rel="nofollow noopener">Open link</a>':esc_html($m[$k])).'</dd>';$html.='</dl>';
 if(in_array($type,array('lost','free','directory','business','competition'),true)){$closed=in_array(strtolower($m['status']??''),array('closed','collected','reunited','cancelled'),true);if($closed)$html.='<p>This listing is closed.</p>';elseif(is_user_logged_in()){$html.='<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tuc_contact"><input type="hidden" name="post" value="'.$id.'">'.wp_nonce_field('tuc-contact-'.$id,'_wpnonce',true,false).'<label>Private message to editors<textarea name="message" rows="3" maxlength="2000" required></textarea></label><button>'.esc_html($type==='free'?'I want this':($type==='lost'?'This might be mine':'Contact / respond')).'</button><p>Only editors see your message. They coordinate contact; your email is not shown publicly.</p></form>';if(isset($_GET['contact_sent']))$html.='<p role="status">Message received. Editors will review it.</p>';}else $html.='<p><a href="'.esc_url(wp_login_url(get_permalink($id))).'">Sign in to respond privately</a></p>';}
 return $content.$html.'</section>';
},9);
add_action('admin_post_tuc_contact',function(){check_admin_referer('tuc-contact-'.absint($_POST['post']??0));$id=absint($_POST['post']??0);$m=(array)get_post_meta($id,'_tuc_local',true);$type=get_post_meta($id,'_tuc_type',true);if(get_post_status($id)!=='publish'||post_password_required($id)||!in_array($type,array('lost','free','directory','business','competition'),true)||in_array(strtolower($m['status']??''),array('closed','collected','reunited','cancelled'),true))tue_notice('This listing is unavailable.');$text=sanitize_textarea_field(wp_unslash($_POST['message']??''));if(strlen($text)<5||strlen($text)>2000)tue_notice('Add a message between 5 and 2,000 characters.');global $wpdb;$uid=get_current_user_id();if(get_transient('tuc-contact-'.$uid))tue_notice('Please wait a minute before sending another message.');$ok=$wpdb->replace(tue_table(),array('user_id'=>$uid,'post_id'=>$id,'tool'=>'claim','scope'=>hash('sha256','local-contact-'.$id),'value'=>$text,'state'=>'open','updated_at'=>current_time('mysql',true)));if(!$ok)tue_notice('Could not save your message.');set_transient('tuc-contact-'.$uid,1,60);wp_safe_redirect(add_query_arg('contact_sent',1,get_permalink($id)));exit;});
// Local listings cannot go live without the details readers need.
function tuc_local_missing($type,$m){
 $required=array('event'=>array('organisation','venue','start','end','area','category','price','source','status'),'directory'=>array('organisation','locality','source','status'),'business'=>array('organisation','business_change','locality','source','status'),'planning'=>array('area','source','status'),'schools'=>array('organisation','area','source'),'sport'=>array('organisation','area','source'),'lost'=>array('locality','status'),'free'=>array('locality','collection','removal','vehicle','status'),'competition'=>array('rules','sponsor','prize','start','end','status'));
 $missing=array();foreach($required[$type]??array() as $key)if(empty($m[$key]))$missing[]=tuc_fields()[$key];
 if(!empty($m['area'])&&!isset(tur_areas()[$m['area']]))$missing[]='a valid CR postcode district';
 if(!empty($m['start'])&&!empty($m['end'])&&strtotime($m['end'])<=strtotime($m['start']))$missing[]='an end time after the start';return $missing;
}
add_filter('wp_insert_post_data',function($data,$postarr){
 if($data['post_type']!=='post'||!in_array($data['post_status'],array('publish','future'),true))return $data;
 $type=get_post_meta($postarr['ID']??0,'_tuc_type',true);$m=(array)get_post_meta($postarr['ID']??0,'_tuc_local',true);
 if(!empty($_POST['tuc_local_nonce'])&&wp_verify_nonce($_POST['tuc_local_nonce'],'tuc-local')){$type=sanitize_key($_POST['tuc_type']??'news');$m=wp_unslash($_POST['tuc_local']??array());}
 $missing=tuc_local_missing($type,$m);if($missing){$data['post_status']='draft';set_transient('tuc-missing-'.get_current_user_id(),implode(', ',$missing),120);}return $data;
},10,2);
add_action('admin_notices',function(){$k='tuc-missing-'.get_current_user_id();$m=get_transient($k);if($m){echo '<div class="notice notice-error"><p>Listing saved as a draft. Before publishing, add: '.esc_html($m).'.</p></div>';delete_transient($k);}});
add_filter('wp_privacy_personal_data_exporters',function($e){$e['todayuk-community']=array('exporter_friendly_name'=>'TodayUK contributions and quiz entries','callback'=>function($email,$page=1){$u=get_user_by('email',$email);$data=array();if($u&&$page===1){global $wpdb;$tips=get_posts(array('post_type'=>'tuc_tip','post_status'=>'private','author'=>$u->ID,'numberposts'=>-1));$entries=$wpdb->get_results($wpdb->prepare('SELECT quiz_id,area,score,entered_at FROM '.$wpdb->prefix.'todayuk_quiz_entries WHERE user_id=%d',$u->ID),ARRAY_A);$data[]=array('group_id'=>'todayuk-community','group_label'=>'TodayUK contributions and quiz','item_id'=>'todayuk-community-'.$u->ID,'data'=>array(array('name'=>'Submissions','value'=>wp_json_encode(array_map(function($p){return array('original'=>get_post_meta($p->ID,'_tuc_original',true),'status'=>get_post_meta($p->ID,'_tuc_state',true));},$tips))),array('name'=>'Quiz entries','value'=>wp_json_encode($entries))));}return array('data'=>$data,'done'=>true);});return $e;});
add_filter('wp_privacy_personal_data_erasers',function($e){$e['todayuk-community']=array('eraser_friendly_name'=>'TodayUK contributions and quiz entries','callback'=>function($email){$u=get_user_by('email',$email);$retained=false;if($u){global $wpdb;$retained=(bool)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.$wpdb->prefix.'todayuk_quiz_entries WHERE user_id=%d',$u->ID))||count(get_posts(array('post_type'=>'tuc_tip','post_status'=>'private','author'=>$u->ID,'numberposts'=>1)))>0;}return array('items_removed'=>false,'items_retained'=>$retained,'messages'=>$retained?array('Contribution originals, editorial audit and competition records need an editor to assess redaction and prize/audit retention. No automated erasure of these records has occurred.') :array(),'done'=>true);});return $e;});

add_filter('todayuk_engagement_config',function($c,$id){
 if($c['mode']!=='auto')return $c;$type=get_post_meta($id,'_tuc_type',true);$m=(array)get_post_meta($id,'_tuc_local',true);
 if($type==='planning')$c['tools'][]='nimby';if($type==='event'){$c['tools'][]='attendance';if(!empty($m['start'])){$c['event_date']=substr($m['start'],0,10);$c['tools'][]='remind';}}
 if($type==='lost')$c['tools'][]='seen';$c['tools']=array_values(array_unique($c['tools']));return $c;
},10,2);
