<?php
if(!defined('ABSPATH'))exit;
require_once __DIR__.'/launch-model.php';
add_action('init',function(){foreach(array('tul_campaign'=>'Campaign briefs','tul_org'=>'Commercial relationships')as $type=>$label)register_post_type($type,array('label'=>$label,'public'=>false,'show_ui'=>false));});
function tul_audit($id,$action){add_post_meta($id,'_tul_audit',array('time'=>gmdate('c'),'actor'=>get_current_user_id(),'action'=>$action));}
function tul_form($action){echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="'.$action.'">';wp_nonce_field($action);}
function tul_field($key,$label,$value='',$type='text',$required=false){echo '<p><label>'.esc_html($label).'<input class="regular-text" style="display:block" type="'.esc_attr($type).'" name="'.esc_attr($key).'" value="'.esc_attr($value).'" '.($required?'required':'').'></label></p>';}
function tul_guard($action){if(!current_user_can('manage_options'))wp_die('Not allowed.',403);check_admin_referer($action);}
function tul_back($tab){wp_safe_redirect(admin_url('admin.php?page=todayuk-operations&tab='.$tab.'&saved=1'));exit;}
add_action('admin_menu',function(){add_menu_page('TodayUK operations','TodayUK operations','manage_options','todayuk-operations','tul_admin','dashicons-chart-area',27);});
function tul_admin(){if(!current_user_can('manage_options'))return;$tab=sanitize_key($_GET['tab']??'health');echo '<div class="wrap" style="max-width:1150px"><h1>TodayUK operations</h1><nav>';foreach(array('health'=>'Launch & health','ads'=>'Ad placements','campaigns'=>'Campaign briefs','bridge'=>'Commercial handoff')as $key=>$name)echo '<a class="button" href="'.esc_url(admin_url('admin.php?page=todayuk-operations&tab='.$key)).'">'.esc_html($name).'</a> ';echo '</nav>';if(isset($_GET['saved']))echo '<p role="status">Saved.</p>';if($tab==='ads')tul_ads_admin();elseif($tab==='campaigns')tul_campaign_admin();elseif($tab==='bridge')tul_bridge_admin();else tul_health();echo '</div>';}
function tul_ads_admin(){
 $a=(array)get_option('tul_ads',array());echo '<h2>Google Ad Manager placements</h2><p>Digital Unicorn house ads fill space until a Google ad is returned. Ad Manager remains the source of truth for bookings, guarantees, forecasts, delivery and revenue.</p><p><a href="https://admanager.google.com/" target="_blank" rel="noopener">Open Google Ad Manager</a></p>';tul_form('tul_ads_save');
 foreach(tul_slots()as $key=>$label)tul_field($key,$label.' · /network/ad-unit',$a[$key]??'');echo '<p><label><input type="checkbox" name="enabled" value="1" '.checked(!empty($a['enabled']),true,false).'> Enable configured Google ad units</label></p><p>Enable only after Ad Manager, AdSense linkage and a supported consent platform are verified. Without a valid consent signal, Google is not requested and house ads remain. No reader identity or reading history is sent as targeting.</p><button class="button button-primary">Save placements</button></form>';
 echo '<h3>Inventory and targeting</h3><p>Header / leaderboard: 970×90 or 728×90 on desktop, 320×100 or 320×50 on mobile. Rectangle/article: 300×250. Context keys: publication, district, locality, section and placement. These are content labels, not user profiles.</p><p>Use Standard line items for guaranteed impressions and Sponsorship for share of voice; create and forecast these in Google Ad Manager. AdSense competes through its Ad Manager linkage. This site does not estimate guaranteed supply or bill from browser events.</p>';
}
add_action('admin_post_tul_ads_save',function(){tul_guard('tul_ads_save');$a=array('enabled'=>!empty($_POST['enabled']));foreach(tul_slots()as $k=>$v){$raw=trim(wp_unslash($_POST[$k]??''));if($raw&&!tul_unit($raw))tue_notice('Use an Ad Manager path beginning /network/ad-unit.');$a[$k]=tul_unit($raw);}if($a['enabled']&&!count(array_filter(array_diff_key($a,array('enabled'=>1)))))tue_notice('Add a valid unit before enabling.');update_option('tul_ads',$a,false);tul_back('ads');});
add_filter('todayuk_gam_ad_unit',function($old,$slot){$a=(array)get_option('tul_ads',array());return !empty($a['enabled'])?tul_unit($a[$slot]??''):'';},10,2);
add_action('wp_enqueue_scripts',function(){
 $a=(array)get_option('tul_ads',array());if(empty($a['enabled']))return;$id=is_singular('post')?get_queried_object_id():0;$local=$id?(array)get_post_meta($id,'_tuc_local',true):array();$terms=$id?wp_get_post_terms($id,'category',array('fields'=>'slugs')):array();if(is_wp_error($terms))$terms=array();
 $publication='cr';foreach(array('cr','rh','sm','br','tn')as $p)if(in_array($p.'-news',$terms,true))$publication=$p;
 wp_enqueue_script('todayuk-gam',plugins_url('gam.js',__FILE__),array(),'1.4.0',true);wp_localize_script('todayuk-gam','todayukAdContext',array('publication'=>$publication,'district'=>sanitize_key($local['area']??''),'locality'=>sanitize_title($local['locality']??''),'section'=>array_slice($terms,0,6)));
});
function tul_campaign_admin(){
 echo '<h2>Campaign briefs</h2><p>Prepare a booking for trafficking in Google Ad Manager. Saving here does not activate ads, reserve inventory or charge anyone.</p>';tul_form('tul_campaign_save');foreach(array('name'=>'Campaign name','advertiser'=>'Advertiser','creative'=>'Creative asset URL','destination'=>'Click-through URL','start'=>'Start date','end'=>'End date','goal'=>'Impressions, share of voice (%) or days','rate'=>'Agreed rate / currency','targeting'=>'Publication, districts, locality and sections','gam_id'=>'Ad Manager line item ID (when created)')as $k=>$label)tul_field($k,$label,'',in_array($k,array('start','end'))?'date':(in_array($k,array('creative','destination'))?'url':'text'),in_array($k,array('name','advertiser','start','end','goal')));
 echo '<p><label>Booking type <select name="type"><option value="standard">Standard · impression goal</option><option value="sponsorship">Sponsorship · share of voice</option><option value="time">Time-based sponsorship brief</option></select></label></p><p><label>Placement <select name="placement">';foreach(tul_slots()as $k=>$v)echo '<option value="'.$k.'">'.$v.'</option>';echo '</select></label></p><button class="button button-primary">Save campaign brief</button></form><h3>Saved briefs</h3>';
 foreach(get_posts(array('post_type'=>'tul_campaign','post_status'=>'private','numberposts'=>100))as $p){$c=get_post_meta($p->ID,'_tul_campaign',true);echo '<details><summary>'.esc_html($p->post_title.' · '.$c['advertiser'].' · '.$c['start'].' to '.$c['end']).'</summary><dl>';foreach($c as $k=>$v)echo '<dt>'.esc_html(ucwords(str_replace('_',' ',$k))).'</dt><dd>'.esc_html($v).'</dd>';echo '</dl><p>Delivery/revenue: verify in Google Ad Manager. No delivery data imported.</p></details>';}
}
add_action('admin_post_tul_campaign_save',function(){tul_guard('tul_campaign_save');$c=array();foreach(array('name','advertiser','creative','destination','start','end','goal','rate','targeting','gam_id','type','placement')as $k)$c[$k]=sanitize_text_field(wp_unslash($_POST[$k]??''));if(!tul_campaign_valid($c))tue_notice('Check the campaign name, advertiser, dates, goal and placement.');foreach(array('creative','destination')as $k)if($c[$k]&&(!wp_http_validate_url($c[$k])||parse_url($c[$k],PHP_URL_SCHEME)!=='https'))tue_notice('Use a valid public HTTPS creative/destination URL.');$id=wp_insert_post(array('post_type'=>'tul_campaign','post_status'=>'private','post_title'=>$c['name']),true);if(is_wp_error($id))tue_notice('Could not save the brief.');update_post_meta($id,'_tul_campaign',$c);tul_audit($id,'Campaign brief saved, not trafficked');tul_back('campaigns');});
function tul_bridge_admin(){
 echo '<h2>Commercial handoff</h2><p>Only permissioned commercial organisations belong here. Reader profiles, reading histories, community groups and public-sector bodies are excluded. Website domains provide exact matching; records are not merged on a similar name.</p>';tul_form('tul_org_save');foreach(array('organisation'=>'Organisation name','website'=>'Organisation website','contact'=>'Business contact email','permission'=>'Permission evidence / agreed purpose','du_ref'=>'Digital Unicorn organisation reference (if known)')as $k=>$label)tul_field($k,$label,'',$k==='website'?'url':($k==='contact'?'email':'text'),in_array($k,array('organisation','website','permission')));echo '<p><label><input type="checkbox" name="commercial" required> This is a commercial organisation with permission for this handoff</label></p><button class="button button-primary">Prepare handoff</button></form><h3>Relationships</h3>';
 foreach(get_posts(array('post_type'=>'tul_org','post_status'=>'private','numberposts'=>100))as $p){$r=get_post_meta($p->ID,'_tul_org',true);echo '<details><summary>'.esc_html($r['organisation'].' · '.($r['du_ref']?:'Awaiting DU reference')).'</summary><p>TodayUK reference: '.absint($p->ID).' · Matching domain: '.esc_html($r['domain']).'</p><p>Permission: '.esc_html($r['permission']).'</p><p>State: '.esc_html(get_post_meta($p->ID,'_tul_state',true)?:'Prepared').'</p>';tul_form('tul_org_export');echo '<input type="hidden" name="id" value="'.$p->ID.'"><button class="button">Download permissioned handoff</button></form><p>The download is not confirmation that Digital Unicorn received it.</p>';tul_form('tul_org_update');echo '<input type="hidden" name="id" value="'.$p->ID.'">';tul_field('du_ref','Confirmed DU reference',$r['du_ref']);tul_field('conversion','Conversion / outcome reference');echo '<button class="button">Record DU acknowledgement / conversion</button></form><h4>Audit</h4>';foreach(get_post_meta($p->ID,'_tul_audit')as $a)echo '<p>'.esc_html($a['time'].' · '.$a['action']).'</p>';echo '</details>';}
}
add_action('admin_post_tul_org_save',function(){tul_guard('tul_org_save');$r=array('class'=>empty($_POST['commercial'])?'':'commercial');foreach(array('organisation','website','contact','permission','du_ref')as $k)$r[$k]=sanitize_text_field(wp_unslash($_POST[$k]??''));if(!tul_can_handoff($r)||!wp_http_validate_url($r['website'])||($r['contact']&&!is_email($r['contact'])))tue_notice('Use a valid commercial organisation, public website, contact and permission evidence.');$r['domain']=tul_org_key($r['website']);$lock='tul-org-'.hash('sha256',$r['domain']);if(!add_option($lock,'pending','','no'))tue_notice('A relationship already exists for this exact domain. Use its existing record.');$id=wp_insert_post(array('post_type'=>'tul_org','post_status'=>'private','post_title'=>$r['organisation']),true);if(is_wp_error($id)){delete_option($lock);tue_notice('Could not save relationship.');}update_option($lock,$id);update_post_meta($id,'_tul_org',$r);tul_audit($id,'Permissioned handoff prepared');tul_back('bridge');});
add_action('admin_post_tul_org_export',function(){tul_guard('tul_org_export');$id=absint($_POST['id']??0);$r=get_post_meta($id,'_tul_org',true);if(get_post_type($id)!=='tul_org'||!tul_can_handoff($r))wp_die('Not allowed.');tul_audit($id,'Handoff downloaded; delivery unconfirmed');update_post_meta($id,'_tul_state','Downloaded — delivery unconfirmed');nocache_headers();header('Content-Type: application/json');header('Content-Disposition: attachment; filename="todayuk-commercial-'.$id.'.json"');echo wp_json_encode(array('schema'=>1,'todayuk_reference'=>$id,'organisation'=>$r),JSON_PRETTY_PRINT);exit;});
add_action('admin_post_tul_org_update',function(){tul_guard('tul_org_update');$id=absint($_POST['id']??0);if(get_post_type($id)!=='tul_org')wp_die('Not allowed.');$r=get_post_meta($id,'_tul_org',true);$ref=sanitize_text_field(wp_unslash($_POST['du_ref']??''));if(!$ref)tue_notice('Add the confirmed DU reference.');$r['du_ref']=$ref;update_post_meta($id,'_tul_org',$r);$outcome=sanitize_text_field(wp_unslash($_POST['conversion']??''));update_post_meta($id,'_tul_state',$outcome?'Conversion recorded':'DU reference recorded');tul_audit($id,'DU reference '.$ref.($outcome?' · conversion '.$outcome:''));tul_back('bridge');});
add_action('wp_mail_failed',function($error){update_option('tul_mail_health',array('state'=>'failed','at'=>gmdate('c'),'message'=>'WordPress could not send email. Check delivery configuration.'),false);});
add_action('wp_mail_succeeded',function(){update_option('tul_mail_health',array('state'=>'accepted','at'=>gmdate('c'),'message'=>'Mail accepted by transport; inbox receipt remains unverified.'),false);});
function tul_health(){
 global $wpdb;$mail=(array)get_option('tul_mail_health',array('state'=>'unverified','message'=>'Reader setup email failed during testing; delivery repair and inbox receipt still required.'));$a=(array)get_option('tul_ads',array());$post=wp_count_posts('post');$tables=array('Engagement'=>$wpdb->prefix.'todayuk_engagement','Quiz entries'=>$wpdb->prefix.'todayuk_quiz_entries');echo '<h2>Launch and health</h2><p>Live system checks and outstanding acceptance. Passing a code test does not mean a feature has been accepted end to end.</p><table class="widefat striped"><thead><tr><th>Check</th><th>Result</th></tr></thead><tbody>';
 $checks=array('HTTPS'=>is_ssl()?'Current request uses HTTPS':'Check HTTPS','Public articles'=>(string)$post->publish,'Email delivery'=>$mail['message'],'Google Ad Manager'=>empty($a['enabled'])?'House ads only; Ad Manager network and units not verified':'Enabled; paid fill and forecasts must be checked in Google Ad Manager','Commercial bridge'=>'Permissioned export / acknowledgement; automatic DU delivery not connected','Social distribution'=>'Social setup is pending after this release','Paid AI'=>'Not enabled by this release');foreach($tables as $label=>$table)$checks[$label.' storage']=$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$table))===$table?'Available':'Missing — needs repair';foreach($checks as $k=>$v)echo '<tr><td>'.esc_html($k).'</td><td>'.esc_html($v).'</td></tr>';echo '</tbody></table><h3>Participation totals</h3>';
 $count=$wpdb->get_var('SELECT COUNT(*) FROM '.$wpdb->prefix.'todayuk_quiz_entries');echo '<p>Quiz entries: '.absint($count).'. These are recorded entries, not unique site visitors.</p><p><a href="'.esc_url(admin_url('edit.php?page=todayuk-engagement')).'">Reader responses and moderation</a> · <a href="'.esc_url(admin_url('admin.php?page=googlesitekit-dashboard')).'">Analytics in Site Kit</a> · <a href="'.esc_url(admin_url('site-health.php')).'">WordPress Site Health</a></p><h3>Acceptance checklist</h3>';
 $labels=tul_checks();$saved=(array)get_option('tul_acceptance',array());tul_form('tul_acceptance_save');foreach($labels as $k=>$v)echo '<p><label><input type="checkbox" name="checks[]" value="'.$k.'" '.checked(in_array($k,$saved,true),true,false).'> '.esc_html($v).'</label></p>';echo '<p>Tick only after testing. This is a manual acceptance record, not an automatic health score.</p><button class="button">Save verified checks</button></form>';
}
function tul_checks(){return array('reader'=>'Reader email, password setup and reader-only permissions','engagement'=>'Fresh publication includes approved engagement','quiz'=>'Real reader quiz entry, duplicate prevention and winner confirmation','listings'=>'Local listing and private claim flow','ads'=>'Ad Manager linkage, paid fill, consent and house fallback','bridge'=>'DU receipt and conversion reference','analytics'=>'Analytics receipt without duplicate tags','mobile'=>'Homepage keyboard, mobile and readable text','social'=>'Facebook sharing and referrals (deferred)');}
add_action('admin_post_tul_acceptance_save',function(){tul_guard('tul_acceptance_save');update_option('tul_acceptance',array_values(array_intersect(array_keys(tul_checks()),(array)($_POST['checks']??array()))),false);update_option('tul_acceptance_actor',array('user'=>get_current_user_id(),'at'=>gmdate('c')),false);tul_back('health');});
