<?php
if(!defined('ABSPATH'))exit;
function tuc_quiz_admin(){
 if(!current_user_can('manage_options'))return;echo '<div class="wrap"><h1>Weekly local quiz</h1><p>One quiz per week. Include local news and local knowledge. Entries are free. Highest score wins; ties go to the earliest entry. Each confirmed weekly winner earns one point for their home district.</p>';
 if(isset($_GET['created']))echo '<p>Quiz saved. Questions cannot change after entries open.</p>';
 echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'" style="max-width:850px"><input type="hidden" name="action" value="tuc_quiz_create">';wp_nonce_field('tuc-quiz-create');
 foreach(array('title'=>'Quiz title','week'=>'Week commencing (Monday)','open'=>'Entries open','close'=>'Entries close','prize'=>'Donated prize','donor'=>'Prize donor','rules'=>'Eligibility and prize terms')as $k=>$label)echo '<p><label>'.esc_html($label).'<input class="widefat" name="'.$k.'" type="'.($k==='week'?'date':(in_array($k,array('open','close'))?'datetime-local':'text')).'" required></label></p>';
 echo '<p>Times use '.esc_html(wp_timezone_string()).'. Publish only when prize and terms are confirmed. No automatic emails or prize fulfilment.</p><label>Questions<textarea class="widefat" name="questions" rows="10" required placeholder="news | Question | Answer A | Answer B | Answer C | Answer D | 1"></textarea></label><p>One question per line: news or local | question | four distinct answers | correct answer number (1–4). Use 2–20 questions, including both kinds. Do not use the | character within a question.</p><button class="button button-primary">Schedule quiz</button></form><h2>Quizzes</h2>';
 global $wpdb;$quizzes=get_posts(array('post_type'=>'tuc_quiz','post_status'=>'private','numberposts'=>-1));foreach($quizzes as $q){$m=get_post_meta($q->ID,'_tuc_quiz',true);$n=$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.$wpdb->prefix.'todayuk_quiz_entries WHERE quiz_id=%d',$q->ID));echo '<h3>'.esc_html($q->post_title).'</h3><p>'.esc_html($m['week']).' · '.absint($n).' entries · closes '.esc_html(wp_date('j M Y H:i',$m['close'])).'</p>';
 if(get_post_meta($q->ID,'_tuc_cancelled',true)){echo '<p>Cancelled; no district point awarded.</p>';continue;}
 $winner=get_post_meta($q->ID,'_tuc_winner',true);if($winner){echo '<p>Confirmed winner: user '.absint($winner['user_id']).', '.esc_html($winner['area']).', score '.absint($winner['score']).'. Prize fulfilment remains manual.</p>';continue;}
 if(time()>=$m['close']){$best=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.$wpdb->prefix.'todayuk_quiz_entries WHERE quiz_id=%d ORDER BY score DESC,entered_at ASC,id ASC LIMIT 1',$q->ID));if($best){$u=get_userdata($best->user_id);echo '<p>Leading entry: '.esc_html($u?$u->display_name:'Deleted account').' · '.esc_html($best->area).' · score '.absint($best->score).'. Check eligibility before confirming.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tuc_quiz_finish"><input type="hidden" name="quiz" value="'.$q->ID.'">';wp_nonce_field('tuc-quiz-finish-'.$q->ID);echo '<label><input type="checkbox" name="eligible" required value="1"> Winner meets the published terms</label> <button class="button">Confirm winner and district point</button></form>';}else echo '<p>No entries; no winner.</p>';}
 echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tuc_quiz_cancel"><input type="hidden" name="quiz" value="'.$q->ID.'">';wp_nonce_field('tuc-quiz-cancel-'.$q->ID);echo '<p><button class="button">Cancel this quiz</button></p></form>';
 }echo '</div>';
}
add_action('admin_post_tuc_quiz_create',function(){
 check_admin_referer('tuc-quiz-create');if(!current_user_can('manage_options'))wp_die('Not allowed.');$r=wp_unslash($_POST);$questions=tuc_quiz_parse($r['questions']??'');if(!$questions)tue_notice('Use 2–20 valid questions, including news and local knowledge.');
 $week=sanitize_text_field($r['week']??'');$d=DateTimeImmutable::createFromFormat('!Y-m-d',$week,wp_timezone());if(!$d||$d->format('Y-m-d')!==$week||$d->format('N')!=='1')tue_notice('Choose a Monday for the quiz week.');
 $open=DateTimeImmutable::createFromFormat('!Y-m-d\TH:i',$r['open']??'',wp_timezone());$close=DateTimeImmutable::createFromFormat('!Y-m-d\TH:i',$r['close']??'',wp_timezone());if(!$open||!$close||$close<=$open||$close->getTimestamp()<=time()||$open->getTimestamp()<$d->getTimestamp()||$close->getTimestamp()>$d->modify('+7 days')->getTimestamp())tue_notice('Set valid opening and closing times within that week, closing in the future.');
 $m=array('week'=>$week,'open'=>$open->getTimestamp(),'close'=>$close->getTimestamp(),'questions'=>$questions);foreach(array('prize','donor','rules')as $k){$m[$k]=sanitize_text_field($r[$k]??'');if(!$m[$k])tue_notice('Add the prize, donor and eligibility terms.');}$title=sanitize_text_field($r['title']??'');if(!$title)tue_notice('Add a title.');
 $lock='tuc-quiz-week-'.$week;if(!add_option($lock,'creating','','no'))tue_notice('A quiz already exists for that week.');$id=wp_insert_post(array('post_type'=>'tuc_quiz','post_status'=>'private','post_title'=>$title),true);if(is_wp_error($id)){delete_option($lock);tue_notice('Could not save the quiz.');}update_post_meta($id,'_tuc_quiz',$m);update_option($lock,$id);tuc_audit($id,'Quiz scheduled');wp_safe_redirect(add_query_arg('created',1,admin_url('edit.php?page=tuc-quizzes')));exit;
});
function tuc_quiz_page(){
 echo '<h1>Weekly local quiz</h1><p>Test your local knowledge and earn a point for your postcode district. Free to enter.</p>';global $wpdb;$qs=get_posts(array('post_type'=>'tuc_quiz','post_status'=>'private','numberposts'=>-1));$active=null;foreach($qs as $q){$m=get_post_meta($q->ID,'_tuc_quiz',true);if(!get_post_meta($q->ID,'_tuc_cancelled',true)&&$m['open']<=time()&&$m['close']>time()){$active=$q;break;}}
 if(!$active)echo '<p>The next quiz is being prepared. Check back here when it opens.</p>';else{
 $m=get_post_meta($active->ID,'_tuc_quiz',true);echo '<h2>'.esc_html($active->post_title).'</h2><p>Closes '.esc_html(wp_date('j M Y H:i',$m['close'])).' ('.esc_html(wp_timezone_string()).').</p><p>Prize: '.esc_html($m['prize']).' · Donated by '.esc_html($m['donor']).'</p><p>'.esc_html($m['rules']).'</p><p>One entry per reader. Highest score wins; equal scores are decided by earliest submission. Editors confirm eligibility. Your home district is fixed for this entry.</p>';
 if(tuc_signed_in()){$uid=get_current_user_id();$entry=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.$wpdb->prefix.'todayuk_quiz_entries WHERE quiz_id=%d AND user_id=%d',$active->ID,$uid));$home=tur_preferences($uid)['home'];if($entry)echo '<p role="status">Entry received for '.esc_html($entry->area).'. Results are released after closing.</p>';elseif(!$home)echo '<p><a href="'.esc_url(tur_url().'#tur-preferences').'">Choose your home district to enter</a></p>';else{
 echo '<p>Playing for <strong>'.esc_html($home).'</strong></p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="tuc_quiz_enter"><input type="hidden" name="quiz" value="'.$active->ID.'">';wp_nonce_field('tuc-quiz-enter-'.$active->ID);
 foreach($m['questions']as $i=>$q){echo '<fieldset><legend>'.($i+1).'. '.esc_html($q['question']).'</legend>';foreach($q['answers']as $j=>$a)echo '<label><input type="radio" name="answers['.$i.']" value="'.$j.'" required> '.esc_html($a).'</label>';echo '</fieldset>';}
 echo '<button>Submit quiz entry</button></form>';}}
 }
 echo '<h2>CR postcode league</h2>';$points=array();foreach($qs as $q){$w=get_post_meta($q->ID,'_tuc_winner',true);if($w&&!get_post_meta($q->ID,'_tuc_cancelled',true))$points[$w['area']]=($points[$w['area']]??0)+1;}arsort($points);if(!$points)echo '<p>The first district point will appear after a weekly winner is confirmed.</p>';else{echo '<table><thead><tr><th>District</th><th>Weekly wins</th></tr></thead><tbody>';foreach($points as $area=>$n)echo '<tr><td>'.esc_html($area).'</td><td>'.absint($n).'</td></tr>';echo '</tbody></table>';}
 if(is_user_logged_in()){echo '<h2>Your past results</h2>';foreach($qs as $q){$m=get_post_meta($q->ID,'_tuc_quiz',true);if($m['close']>time())continue;$e=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.$wpdb->prefix.'todayuk_quiz_entries WHERE quiz_id=%d AND user_id=%d',$q->ID,get_current_user_id()));if($e)echo '<p>'.esc_html($q->post_title).' — '.absint($e->score).' / '.count($m['questions']).(get_post_meta($q->ID,'_tuc_cancelled',true)?' (cancelled)':'').'</p>';}}
}
add_action('admin_post_tuc_quiz_enter',function(){
 $id=absint($_POST['quiz']??0);check_admin_referer('tuc-quiz-enter-'.$id);$m=get_post_meta($id,'_tuc_quiz',true);$uid=get_current_user_id();$area=tur_preferences($uid)['home'];if(get_post_type($id)!=='tuc_quiz'||!is_array($m)||get_post_meta($id,'_tuc_cancelled',true)||time()<$m['open']||time()>=$m['close'])tue_notice('This quiz is not open.');if(!isset(tur_areas()[$area]))tue_notice('Choose your home district first.');$score=tuc_quiz_score($m['questions'],(array)($_POST['answers']??array()));if($score===false)tue_notice('Answer every question using the displayed choices.');
 global $wpdb;$t=$wpdb->prefix.'todayuk_quiz_entries';$ok=$wpdb->query($wpdb->prepare("INSERT IGNORE INTO $t (quiz_id,user_id,area,score,entered_at) VALUES (%d,%d,%s,%d,%s)",$id,$uid,$area,$score,current_time('mysql',true)));if($ok===false)tue_notice('Your entry could not be saved. Please retry.');wp_safe_redirect(tuc_url('quiz'));exit;
});
add_action('admin_post_nopriv_tuc_quiz_enter',function(){auth_redirect();});
add_action('admin_post_tuc_quiz_finish',function(){
 $id=absint($_POST['quiz']??0);check_admin_referer('tuc-quiz-finish-'.$id);if(!current_user_can('manage_options'))wp_die('Not allowed.');$m=get_post_meta($id,'_tuc_quiz',true);if(!$m||time()<$m['close']||empty($_POST['eligible'])||get_post_meta($id,'_tuc_cancelled',true))tue_notice('Wait for the quiz to close and verify eligibility.');global $wpdb;$w=$wpdb->get_row($wpdb->prepare('SELECT user_id,area,score FROM '.$wpdb->prefix.'todayuk_quiz_entries WHERE quiz_id=%d ORDER BY score DESC,entered_at ASC,id ASC LIMIT 1',$id),ARRAY_A);if(!$w)tue_notice('There are no entries.');if(!get_post_meta($id,'_tuc_winner',true)){update_post_meta($id,'_tuc_winner',$w);tuc_audit($id,'Winner confirmed');}wp_safe_redirect(admin_url('edit.php?page=tuc-quizzes'));exit;
});
add_action('admin_post_tuc_quiz_cancel',function(){$id=absint($_POST['quiz']??0);check_admin_referer('tuc-quiz-cancel-'.$id);if(!current_user_can('manage_options')||get_post_type($id)!=='tuc_quiz')wp_die('Not allowed.');if(get_post_meta($id,'_tuc_winner',true))tue_notice('A winner has already been confirmed.');update_post_meta($id,'_tuc_cancelled',true);tuc_audit($id,'Cancelled');wp_safe_redirect(admin_url('edit.php?page=tuc-quizzes'));exit;});
