'use client';
import {useEffect,useState} from 'react';
import Discovery from './discovery';
import {Button} from '@/components/ui/button';
type Data={workspace:{name:string};nodes:{id:string;code:string;name:string;kind:string}[];tags:{id:string;label:string;category:string}[];membership:{role:string};audits:{id:string;entity_table:string;action:string;created_at:string}[]};
export default function Live(){const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(true);
 async function refresh(){setBusy(true);setError('');try{const r=await fetch('/api/newsroom',{cache:'no-store'});const d=await r.json() as Data & {error?:string};if(!r.ok){setData(null);setError(d.error??'Could not load the newsroom.')}else setData(d)}catch{setData(null);setError('Could not reach the newsroom. Please retry.')}finally{setBusy(false)}}
 useEffect(()=>{void refresh()},[]);
 return <><header className="masthead"><a href="/" className="brand">TODAY<span>UK</span></a><a href="/signin">Newsroom account</a></header><main className="desk"><div className="intro"><div><p className="eyebrow">Live workspace</p><h1>CR News newsroom</h1></div><Button onClick={refresh} disabled={busy}>{busy?'Loading…':'Refresh'}</Button></div>{error&&<section className="panel"><p role="alert">{error}</p><a className="pill inline-block mt-4" href="/signin">Sign in to the newsroom →</a></section>}{data&&<><p className="pill inline-block">Connected · {data.workspace.name} · {data.membership.role}</p><a className="pill inline-block mt-4 ml-3" href="/research">Open research desk →</a> · <a href="/editorial">Drafts & review →</a> · <a href="/publishing">Publishing desk →</a><Discovery/><details className="mt-8"><summary className="cursor-pointer font-semibold">Workspace structure and activity</summary><div className="grid"><section className="panel"><h2>Publication & districts</h2>{data.nodes.map(n=><div className="row" key={n.id}><strong>{n.code}</strong><span>{n.name}</span></div>)}</section><section className="panel"><h2>Shared taxonomy</h2>{data.tags.map(t=><div className="row" key={t.id}><span>{t.label}</span><span className="muted">{t.category}</span></div>)}</section></div><section className="panel mt-6"><h2>Recent activity</h2>{data.audits.map(a=><div className="row" key={a.id}><span>{a.action.toLowerCase()} · {a.entity_table.replaceAll('_',' ')}</span><time>{new Date(a.created_at).toLocaleString('en-GB')}</time></div>)}</section></details></>}</main></>;
}
