'use client';
import {useEffect,useState} from 'react';
type Draft={id:string;headline:string;revision:number;status:string};
type Delivery={id:string;draft_id:string;draft_revision:number;headline:string;state:string;wordpress_url:string|null;message:string};
type Data={configured:boolean;destination:string|null;deliveries:Delivery[];role:string};
export default function Publishing(){const [data,setData]=useState<Data|null>(null),[drafts,setDrafts]=useState<Draft[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState('');
 async function load(){try{const [a,b]=await Promise.all([fetch('/api/publishing',{cache:'no-store'}),fetch('/api/editorial',{cache:'no-store'})]);const x=await a.json() as Data&{error?:string},y=await b.json() as {drafts:Draft[];error?:string};if(!a.ok||!b.ok)throw Error(x.error||y.error);setData(x);setDrafts(y.drafts);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load publishing desk.');}}
 useEffect(()=>{void load();},[]);
 async function act(action:string,d?:Draft){setBusy(true);setMessage('');try{const r=await fetch('/api/publishing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id:d?.id,revision:d?.revision})});const x=await r.json() as {error?:string;message:string};if(!r.ok)throw Error(x.error);setMessage(x.message);setConfirm('');}catch(e){setMessage(e instanceof Error?e.message:'Transfer failed.');}finally{await load();setBusy(false);}}
 return <><header className="masthead"><a className="brand" href="/live">TODAY<span>UK</span></a><a href="/editorial">← Drafts & review</a></header><main className="desk editorial-page"><p className="eyebrow">PUBLISHING DESK</p><h1>WordPress handoff</h1><p>Send an approved revision as a WordPress draft, inspect it there, then explicitly publish it.</p>{message&&<p className="note" role="status">{message}</p>}{!data&&!message&&<p>Loading publishing desk…</p>}{data&&<><section className="panel"><h2>{data.configured?'Destination configured':'WordPress is not connected yet'}</h2><p>{data.destination??'The WordPress website and a dedicated publishing connection are needed before articles can be sent.'}</p>{data.configured&&data.role==='owner'&&<button disabled={busy} onClick={()=>void act('check')}>Check connection</button>}</section><h2>Approved stories</h2>{!drafts.some(d=>d.status==='approved')&&<p>No approved stories yet. Complete the editorial checks and review first.</p>}{drafts.filter(d=>d.status==='approved').map(d=>{const delivery=data.deliveries.find(x=>x.draft_id===d.id);return <article className="panel my-4" key={d.id}><h3>{d.headline}</h3><p>Approved revision {d.revision}</p>{delivery?<><p>WordPress transfer: <strong>{delivery.state}</strong> · revision {delivery.draft_revision}</p>{delivery.wordpress_url&&<a href={delivery.wordpress_url} target="_blank" rel="noreferrer">Open WordPress article ↗</a>}{delivery.state==='draft'&&delivery.draft_revision===d.revision&&data.role==='owner'&&(confirm===d.id?<div className="note"><p>Publish “{d.headline}” publicly on {data.destination}?</p><button disabled={busy} onClick={()=>void act('publish',d)}>Confirm public publication</button> <button onClick={()=>setConfirm('')}>Cancel</button></div>:<p><button disabled={busy||!data.configured} onClick={()=>setConfirm(d.id)}>Publish approved article…</button></p>)}</>:data.role==='owner'&&<button disabled={busy||!data.configured} onClick={()=>void act('send',d)}>Send as WordPress draft</button>}</article>;})}<h2>Transfer history</h2>{data.deliveries.map(d=><article key={d.id} className="panel my-4"><h3>{d.headline}</h3><p>{d.state} · revision {d.draft_revision}</p><p>{d.message}</p>{['uncertain','sending','publishing'].includes(d.state)&&<p>Check WordPress before retrying. Automatic resend is blocked to prevent duplicate articles.</p>}{d.wordpress_url&&<a href={d.wordpress_url} target="_blank" rel="noreferrer">Open WordPress article ↗</a>}</article>)}{!data.deliveries.length&&<p>No articles have been sent.</p>}</>}<p><button disabled={busy} onClick={()=>void load()}>Refresh publishing desk</button></p></main></>;
}
